### ISSUE TITLE
OpenAPI skill does not support Payload

### ISSUE THREAD

**Issue by thomasgobin** [microsoft/semantic-kernel#1423]
The current implementation of OpenApi skill does not support Payload, only GET parameters.

As many APIs are using the payload, this is clearly a must from my point of view.

I am going to submit a Pull request to enable a first version of support for payload support if it's ok for you ?

**Comment by frederikrosenberg** [comment]
I have been testing the open PR for this issue, and have found something which is missing. Enum values are not included in the payload description causing the AI to try and guess a valid value.

The could be address in a separate PR instead of increasing the scope of the current PR.

**Comment by lemillermicrosoft** [comment]
Can you confirm this has been resolved and close @SergeyMenshykh ?

**Comment by SergeyMenshykh** [comment]
Support for payloads for PUT and POST operations has been available since almost day one SK OpenAPI functionality was introduced - [link](https://github.com/microsoft/semantic-kernel/blob/cfebcaec6c1656f2c129ca3e40442c0ace9495e5/dotnet/samples/KernelSyntaxExamples/Example22_OpenApiSkill_AzureKeyVault.cs#L86C7-L86C132). However, to use it, clients need to know its shape/schema in advance to build and include it as an argument in the arguments collection.

Recently, we extended OpenAPI functionality to support dynamic payload building, eliminating the need to know the payload schema in advance. More details can be found here - [link](https://github.com/microsoft/semantic-kernel/blob/main/docs/decisions/0005-open-api-dynamic-payload-and-namespaces.md).

Closing the issue for now. Please feel free to open another one if it doesn't suit your scenario.
