### ISSUE TITLE
Smeantic-Kernal NuGets fail in Function Apps

### ISSUE THREAD

**Issue by wrharper-AASP** [microsoft/semantic-kernel#1793]
**Describe the bug**
If you use Azure Function Apps with version 15.230531.5-preview it will work.
Every version past that gives the error in the screenshot. 0.15.320609.2-preview and onward.

**To Reproduce**
Just make an Azure Function App in Visual Studio 2022 as a httptrigger and import these files. After you run it, you will see the error.

**Expected behavior**
Needs to be able to load latest versions.

**Screenshots**
![image](https://github.com/microsoft/semantic-kernel/assets/117128832/fbbdc315-ef58-4812-b135-75bdbc7276c1)

**Desktop (please complete the following information):**
In descriptions already, on windows 11

**Comment by wrharper-AASP** [comment]
I believe this is the problem in the patch notes:
Upgrade System.Text.Json and Microsoft.Extensions.Logging versions to 7.0 by @stephentoub in https://github.com/microsoft/semantic-kernel/pull/1297

**Comment by wrharper-AASP** [comment]
I reverted changes (manually created a build) the best I could from: https://github.com/microsoft/semantic-kernel/pull/1297/commits/bc7627ae41dac088d0990a8e7cd0bff3d902041e until this is resolved.

**Comment by ericstj** [comment]
cc @fabiocav
AzureFunctions has a managed host and loads functions into the same process -- as a result the host will *pin* a number of the assemblies it uses since it needs to share types from those assemblies with functions and agree on the type definitions.  As a result - those functions cannot upgrade the assemblies pinned by the host.  It looks like Azure functions doesn't do anything to notify the function project when it's in a state where it's referenced versions of these that cannot be loaded by the host.

Here's a repro project for the broken in-process azure function: 
[FunctionApp1.zip](https://github.com/microsoft/semantic-kernel/files/11919528/FunctionApp1.zip)

Azure functions did create a solution for this problem, and that's the "Isolated" function model.  When you create your function, make sure to select "Isolated" as shown below.
<img width="470" alt="image" src="https://github.com/microsoft/semantic-kernel/assets/8918108/3c9bb388-b2cf-4bbc-9d39-552bb9653482">

Here's a repro project for the working isolated process azure function:
[FunctionApp2.zip](https://github.com/microsoft/semantic-kernel/files/11919532/FunctionApp2.zip)

Here's more detail on the different types of Azure functions: https://learn.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide

@fabiocav it would be nice if Azure Functions SDK would notify users when they were in this state - either with a better runtime exception - or even better - a build time error letting them know the application was referencing an assembly version that wouldn't be loadable in the shared host.

**Comment by wrharper-AASP** [comment]
I guess the only choice is to wait for in-process to get fixed. Isolated won't work for what I am doing.

**Comment by wrharper-AASP** [comment]
the custom build I have created is working. so I will just use it until in-process is fixed.
