### ISSUE TITLE
semantic-kernel\samples\notebooks\dotnet\00-getting-started.ipynb - Step 4 throws error: Error: Invalid request: The request is not valid, HTTP status: 400

### ISSUE THREAD

**Issue by dipteshbosedxc** [microsoft/semantic-kernel#1940]
**Describe the bug**
semantic-kernel\samples\notebooks\dotnet\00-getting-started.ipynb - Step 4 throws error: Error: Invalid request: The request is not valid, HTTP status: 400

**To Reproduce**

**Expected behavior**
Should return with a response from the model

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - IDE: [e.g. Visual Studio, VS Code]
 - NuGet Package Version [e.g. 0.1.0]

**Additional context**

**Comment by TaoChenOSU** [comment]
Hello @dipteshbosedxc, could you provide which model you are using? You will see this error if you are using a chat completion model rather than a text completion model. 

Hope this helps! I will also update the ReadMe.

**Comment by TaoChenOSU** [comment]
Related issue: https://github.com/microsoft/semantic-kernel/issues/1896

**Comment by jouniheikniemi** [comment]
For what it's worth, at least for the most part (i.e., haven't tested every sample) you can patch around this by replacing the builder.WithAzureTextCompletion... line by `builder.WithAzureChatCompletionService(model, azureEndpoint, apiKey, alsoAsTextCompletion: true);`, and you can use a gpt-3.5 deployment name as `model`.

**Comment by glahaye** [comment]
As mentioned above, this is most likely due to using a chat completion model (e.g. "gpt-35-turbo" with Azure Open AI or "gpt-3.5-turbo" with OpenAI.com) where a text completion one was expected (e,g, ""text-davinci-003).

Either change the model or use WithAzureChatCompletionService instead of WithAzureTextCompletion (I suggest the latter and this will be the default starting soon)
