### ISSUE TITLE
Custom Endpoint for OpenAI

### ISSUE THREAD

**Issue by victor-v-rad** [microsoft/semantic-kernel#2145]
Companies create internal API proxies to avoid direct calls to https://api.openai.com/. The Semantic Kernel does not provide the possibility to specify a custom endpoint. Please see the picture.
<img width="1171" alt="image" src="https://github.com/microsoft/semantic-kernel/assets/106504/2eb8ac3d-f74f-4451-84ac-3e49e33b8a4d">

Please create this possibility.

**Comment by victor-v-rad** [comment]
Created according issue for Azure SDK
https://github.com/Azure/azure-sdk-for-net/issues/37794

**Comment by gingters** [comment]
Just to second that, if you want to use Semantic Kernel to enrich your Blazor WebAssembly application with AI capabilities, you for sure don't want to provide your API key to the browser ;)

It's easy to add a Yarp.ReverseProxy to your server that authenticatces your users based on your normal auth mode (Cookies, Tokens etc.) redirects all calls to /openai to your Azure OpenAI endpoints and add the secret Api Key to these requests on the server side, but since you can't set the base url for the pure OpenAI endpoint its sadly not possible to use these from your web application atm.

**Comment by JadynWong** [comment]
https://github.com/microsoft/semantic-kernel/issues/1445#issuecomment-1590980113

https://github.com/microsoft/semantic-kernel/issues/1445#issuecomment-1605622515

**Comment by craigomatic** [comment]
> Temporary solution
> 
> [#1445 (comment)](https://github.com/microsoft/semantic-kernel/issues/1445#issuecomment-1590980113)
> 
> [#1445 (comment)](https://github.com/microsoft/semantic-kernel/issues/1445#issuecomment-1605622515)
> 
> ```cs
> private class ProxyOpenAIHandler : HttpClientHandler
> {
>     protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
>     {
>         if (request.RequestUri != null && request.RequestUri.Host.Equals("api.openai.com", StringComparison.OrdinalIgnoreCase))
>         {
>             // your proxy url
>             request.RequestUri = new Uri($"https://openai.yourproxy.com/{request.RequestUri.PathAndQuery}");
>         }
>         return base.SendAsync(request, cancellationToken);
>     }
> }
> 
> 
> var kernel = Kernel.Builder
>         .WithOpenAIChatCompletionService("<model-id>", "<api-key>", httpClient: new HttpClient(new ProxyOpenAIHandler()))
>         .Build();
> ```

This is the solution I would recommend also.

Does this unblock both of your scenarios @victor-v-rad and @gingters ?

For the Chat Copilot (fka Copilot Chat and now [lives here](https://github.com/microsoft/chat-copilot/)) you'd need to either modify the deployment scripts to pass your proxy through as a config value that your code picks up, or just leave as-is and hardcode your proxy. In both cases the code @JadynWong describes above should enable this.

**Comment by victor-v-rad** [comment]
Thank you @JadynWong for sharing the code snippets. That unblocks me. There is also standard proxy configuration in Azure SDK.
https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/samples/Configuration.md#configuring-a-proxy 
It might be good to mentioned README.md or here in appsettings.json > AIService 
https://github.com/microsoft/chat-copilot/blob/main/webapi/appsettings.json#L22-L48

@craigomatic Thank you for sharing new Chat Copilot repo. It worth celebrating

**Comment by JadynWong** [comment]
Of course, that solves your problem.

**Comment by the-xentropy** [comment]
For anyone searching for a quick and easy way to do this in Python:

```
import semantic_kernel as sk
from semantic_kernel.connectors.ai.open_ai import OpenAIChatCompletion

service = OpenAIChatCompletion(ai_model_id="<MODEL NAME>", api_key=<API KEY>)
service.client.base_url = "<API URL>"
kernel.add_chat_service(
    "chat_completion",
    service,
)
```

The underlying AsyncOpenAI client the semantic-kernel wrapper uses has the option to provide the base url in the initializer, but semantic-kernel doesn't expose it as a keyword parameter  in the wrapper init function. You can still set it post-initialization by accessing the wrapper's underlying OpenAI client though.

I think it would be preferable for this keyword argument to simply be exposed in the wrapper init function, since this is prone to breakages if e.g. internal variable names change, but it works and is a 30 second one-line fix so it's good enough for me for now.

**Comment by Prakashssv-India** [comment]
> For anyone searching for a quick and easy way to do this in Python:
> 
> ```
> import semantic_kernel as sk
> from semantic_kernel.connectors.ai.open_ai import OpenAIChatCompletion
> 
> service = OpenAIChatCompletion(ai_model_id="<MODEL NAME>", api_key=<API KEY>)
> service.client.base_url = "<API URL>"
> kernel.add_chat_service(
>     "chat_completion",
>     service,
> )
> ```
> 
> The underlying AsyncOpenAI client the semantic-kernel wrapper uses has the option to provide the base url in the initializer, but semantic-kernel doesn't expose it as a keyword parameter in the wrapper init function. You can still set it post-initialization by accessing the wrapper's underlying OpenAI client though.
> 
> I think it would be preferable for this keyword argument to simply be exposed in the wrapper init function, since this is prone to breakages if e.g. internal variable names change, but it works and is a 30 second one-line fix so it's good enough for me for now.

**kernel**.add_chat_service(
"chat_completion",
service,
)

where is the kernel is been initialized. should i need to import any library?

**Comment by dinesh-coupa** [comment]
Can anyone help with Python code for custom openai endpoint using bearer token auth and not api_key ?
