### ISSUE TITLE
.Net: Python: implement stepwise planner

### ISSUE THREAD

**Issue by joowon-dm-snu** [microsoft/semantic-kernel#2221]
@alexchaomander @awharrison-28 
does your team has plan for stepwise planner?
if nothing decided, i think i can take it ;)

++ I'm curious about the future plans on python now that the C# Telemetry feature has been officially released since the main product of the company I work for is logging and analyzing interactions between users and LLM-based products. If telemetry or callback feature is also added to Python, I'd like to know if it would be possible to commit our product's integration.

**Comment by alexchaomander** [comment]
@joowon-dm-snu Right now no one has taken this up yet! Of course, if you have the time, you're welcome to do it! 

From my perspective, after these planners, the telemetry and pre/post hooks integrations (i.e. callbacks) are going to be the next things to tackle so that Python SK is truly at parity with C#. Those things are still being architected in C# but the plan is once that happens, we'll want to bring the same to Python. 

@dmytrostruk @RogerBarreto for visibility as they are working on the telemetry and pre/post hooks.

**Comment by matthewbolanos** [comment]
Closing since this is now complete
