### ISSUE TITLE
.Net: Inconsistent naming between WithMemoryStorage and IMemoryStore

### ISSUE THREAD

**Issue by stephentoub** [microsoft/semantic-kernel#2607]
A small thing, but it's strange that we have WithMemoryStorage/IMemoryStore, rather than WithMemoryStore/IMemoryStore or WithMemoryStorage/IMemoryStorage. (Personally, I prefer WithMemoryStore/IMemoryStore.)

**Comment by nacharya1** [comment]
@dluc - thoughts on this change?

**Comment by dluc** [comment]
agreed, I don't know why we chose "memory store" rather than "memory storage". My preference would be `WithMemory/IMemory` but also renaming all the derived classes, e.g. `AzureCognitiveSearchMemory` to `AzureCognitiveSearchMemory`.

I wish we did remove the memory from the kernel in v1, in favor of a generic plugin. Since longer term we will (don't know how we're going to face the breaking change though), I don't mind leaving things as they are or making a minor change e.g. renaming just `WithMemoryStorage` to `WithMemoryStore`. In any case it's a breaking change, so I don't know if that's worth the pain.

**Comment by markwallace-microsoft** [comment]
All .Net issues prior to 1-Dec-2023 are being closed. Please re-open, if this issue is still relevant to the .Net Semantic Kernel 1.x release. In the future all issues that are inactive for more than 90 days will be labelled as 'stale' and closed 14 days later.
