### ISSUE TITLE
Java: API - What about having the ability to pass different types of variable in the SKContext 

### ISSUE THREAD

**Issue by agoncal** [microsoft/semantic-kernel#2669]
Today `SKContext` only allows String (which makes sense):

```java
public interface SKContext extends Buildable {
    SKContext setVariable(String key, String content);
}
```

So when we pass other type than String, we need to convert them:

```java
myContext.setVariable("myVar", String.valueOf(myInt));
```

What about having helper methods that do the conversion? Something like this for `int`:

```java
public interface SKContext extends Buildable {
    SKContext setVariable(String key, String content);
    SKContext setVariable(String key, int content);
}
```

And just do the conversion in the implementation:

```java
public abstract class AbstractSKContext implements SKContext {
    @Override
    public SKContext setVariable(@NonNull String key, @NonNull String content) {
        variables.setVariable(key, content);
        return getThis();
    }

    @Override
    public SKContext setVariable(@NonNull String key, @NonNull int content) {
        variables.setVariable(key, String.valueOf(content));
        return getThis();
    }
}
```

Nothing major but a few methods would help with the String casting code all over the place.

**Comment by sammiie** [comment]
To enable the ability to pass different types of variables in the SKContext in a Java API, you can utilize generics to make the context more flexible and accommodate various data types. Below, I'll provide a code structure and a diagram to illustrate this solution.

Issue Explanation:

The goal is to enhance the SKContext in a Java API so that it can accept and manage different types of variables.

Solution:

Define a Generic SKContext:
Modify the SKContext class to be generic, allowing it to accept a variety of data types. You can use Java generics to achieve this flexibility.
java

public class SKContext<T> {
    private T data;

    public SKContext(T data) {
        this.data = data;
    }

    public T getData() {
        return data;
    }

    public void setData(T data) {
        this.data = data;
    }
}
Usage of SKContext:
Use the generic SKContext class in your API wherever you need to pass different types of variables. The context can now be instantiated with various data types.
java

// Example usage of SKContext with different data types

// String data
SKContext<String> stringContext = new SKContext<>("Hello, World!");

// Integer data
SKContext<Integer> integerContext = new SKContext<>(42);

// Custom data type
SKContext<MyCustomType> customContext = new SKContext<>(new MyCustomType());
Benefits:

This modification allows the SKContext to be more versatile and adaptable to different use cases. It can hold various data types without the need for separate context classes.
Documentation:

Update the documentation to inform users of the enhanced SKContext and its ability to accept generic data types.
Diagram Structure:

A simplified diagram illustrating the enhanced SKContext with generics:

sql

+-------------------------------------+
|            Java API                 |
|                                     |
|   +-----------------------------+   |
|   |       SKContext<T>         |   |
|   |                           |   |
|   | - data: T                |   |
|   |                           |   |
|   | +-----------------------+ |   |
|   | | Constructor(T data)  | |   |
|   | | getData(): T         | |   |
|   | | setData(T data): void| |   |
|   | +-----------------------+ |   |
|   |                           |   |
|   +-----------------------------+   |
|                                     |
|   +-----------------------------+   |
|   |    Usage Examples          |   |
|   |                           |   |
|   | - String data:            |   |
|   |   SKContext<String>       |   |
|   |                           |   |
|   | - Integer data:           |   |
|   |   SKContext<Integer>      |   |
|   |                           |   |
|   | - Custom data type:       |   |
|   |   SKContext<MyCustomType> |   |
|   |                           |   |
|   +-----------------------------+   |
|                                     |
|   +-----------------------------+   |
|   |       Documentation         |   |
|   |                           |   |
|   |   Enhanced SKContext with  |   |
|   |   Generics                |   |
|   |                           |   |
|   +-----------------------------+   |
|                                     |
+-------------------------------------+
In this diagram:

The "Java API" includes the enhanced SKContext class, which is now generic (SKContext<T>) and can accept various data types.
The "Usage Examples" section demonstrates how different types of data can be used with SKContext.
The "Documentation" section highlights the enhanced SKContext and its generic capabilities.

**Comment by johnoliver** [comment]
Will be done under #3626

**Comment by d3r3kk** [comment]
Completed with the V1.0 work to date.
