### ISSUE TITLE
Python: Function not available: githubplugin.summarizerepository on Python and OpenAI Model not picking up

### ISSUE THREAD

**Issue by amitlals** [microsoft/semantic-kernel#2732]
**Describe the bug**

Running sample app -> GitHub Repo Q&A Bot, while deployment, I encountered two separate errors, 

**First, function not available for while running on python**
[2023-09-06T02:29:24.382Z] Executing 'Functions.completion' (Reason='This function was programmatically called via the host APIs.', Id=e0fb13bb-fbec-4d35-a6b1-dc66b1ba5273)
[2023-09-06T02:29:24.426Z] Completion request
[2023-09-06T02:29:24.432Z] skill_name: GitHubPlugin
[2023-09-06T02:29:24.436Z] Creating kernel and importing skills ['GitHubPlugin']
[2023-09-06T02:29:24.427Z] Python HTTP trigger function processed a request.
[2023-09-06T02:29:24.442Z] Could not find function SummarizeRepository in skill GitHubPlugin
Traceback (most recent call last):
  File "C:\Users\amlal\Desktop\OpenAI-PRoject\SK-Demo\semantic-kernel-main\semantic-kernel-main\samples\python\kernel_http_server\utils\kernel_server.py", line 51, in completion
    sk_func = kernel.skills.get_function(skill_name, function_name)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\amlal\Desktop\OpenAI-PRoject\SK-Demo\semantic-kernel-main\semantic-kernel-main\samples\python\kernel_http_server\.venv\Lib\site-packages\semantic_kernel\skill_definition\read_only_skill_collection.py", line 108, in get_function
    raise KernelException(
**semantic_kernel.kernel_exception.KernelException: (<ErrorCodes.FunctionNotAvailable: 2>, 'Function not available: githubplugin.summarizerepository', None)**

Second, while selecting OpenAI model, it didn't pick up any model in first instance. 

**Expected behavior**
Test the sample app to run on one of my favorite github.com repo, to showcase this usecase

**Screenshots**
![image](https://github.com/microsoft/semantic-kernel/assets/37605691/7a967121-c2bf-4173-912d-fb117158098b)

![image](https://github.com/microsoft/semantic-kernel/assets/37605691/eabf5290-1987-4244-833c-cb3346598f94)

**Platform**
 - OS: Windows
 - IDE: S Code]
 - Language: Python
 - Source: [e.g. NuGet package version 0.1.0, pip package version 0.1.0, main branch of repository]

**Additional context**

**Comment by sammiie** [comment]
To address the issue of the Python function githubplugin.summarizerepository not being available and the OpenAI model not recognizing it, let's follow a structured approach to resolve this issue using code and a diagram:

Issue Explanation:

The problem seems to be that the function githubplugin.summarizerepository is not recognized by the OpenAI model, and there might be an issue with code or configuration.

Solution:

Check Function Implementation:

Review the code where the githubplugin.summarizerepository function is implemented. Ensure that it is correctly defined and exposed as part of your Python package or module.
Import Statement:

Double-check that you are correctly importing the githubplugin module in your code. Verify the import statement to ensure it matches the module's actual location.
Function Usage:

Confirm that you are calling the githubplugin.summarizerepository function correctly with the expected arguments and parameters.
Namespace Conflicts:

Check for any namespace conflicts or naming clashes that might prevent the OpenAI model from recognizing the function. Ensure that the function's name is unique within your codebase.
Function Availability:

Ensure that the githubplugin module is correctly installed and available within your Python environment. You can do this by running the following command:
python

pip install githubplugin
API Configuration:

Verify the configuration of the OpenAI API. Ensure that you are using the correct API key and endpoint URL to interact with the model.
Test with Sample Input:

Create a simple test case with sample input to ensure that the githubplugin.summarizerepository function works as expected in isolation.
Test with OpenAI Model:

Use the function as input to the OpenAI model. Double-check the API request and parameters to ensure that the function is properly integrated.
Diagram Structure:

A simplified diagram to visualize the steps for resolving the issue:

sql

+-----------------------------------------------------+
|                       Issue                         |
|                                                     |
|   +------------------+   +-------------------+      |
|   | Code Review      |   | Import Statement |      |
|   | (Function Impl.) |   | (Namespace Check)|      |
|   +------------------+   +-------------------+      |
|                                                     |
|   +-----------------+   +------------------+       |
|   | Function Usage  |   | Namespace Conflicts|   |
|   | (Parameters)    |   | (Uniqueness Check) |   |
|   +-----------------+   +------------------+       |
|                                                     |
|   +-----------------+   +----------------------+   |
|   | Module Availability | API Configuration   |   |
|   | (pip Install)     | (Key, Endpoint Check)|   |
|   +-----------------+   +----------------------+   |
|                                                     |
|   +-----------------+   +----------------------+   |
|   | Test with Sample |  Test with OpenAI     |   |
|   | Input (Isolation)|  Model (API Request) |   |
|   | (Function Input) |  (Parameters Check)  |   |
|   +-----------------+   +----------------------+   |
|                                                     |
+-----------------------------------------------------+
In this diagram:

Each step in the solution process is outlined, from reviewing code to testing with the OpenAI model.
The diagram helps visualize the structured approach to resolving the issue with the githubplugin.summarizerepository function not being recognized.

**Comment by amitlals** [comment]
Thank you for your response. I tried to add these packages but no success so far.  I am trying to see which package is holding githubplugin, tried below so far. 


`PS C:\Users\amlal\Desktop\OpenAI-PRoject\SK-Demo\semantic-kernel-main\semantic-kernel-main> pip install githubplugin                              
ERROR: Could not find a version that satisfies the requirement githubplugin (from versions: none)
ERROR: No matching distribution found for githubplugin
PS C:\Users\amlal\Desktop\OpenAI-PRoject\SK-Demo\semantic-kernel-main\semantic-kernel-main> pip install azure-semantic-knowledge-extraction
ERROR: Could not find a version that satisfies the requirement azure-semantic-knowledge-extraction (from versions: none)
ERROR: No matching distribution found for azure-semantic-knowledge-extraction
PS C:\Users\amlal\Desktop\OpenAI-PRoject\SK-Demo\semantic-kernel-main\semantic-kernel-main> pip cache purge
Files removed: 601
PS C:\Users\amlal\Desktop\OpenAI-PRoject\SK-Demo\semantic-kernel-main\semantic-kernel-main> pip install --upgrade pip                             
Requirement already satisfied: pip in c:\python311\lib\site-packages (23.2.1)
PS C:\Users\amlal\Desktop\OpenAI-PRoject\SK-Demo\semantic-kernel-main\semantic-kernel-main> pip install azure-semantic-knowledge-extraction
ERROR: Could not find a version that satisfies the requirement azure-semantic-knowledge-extraction (from versions: none)
ERROR: No matching distribution found for azure-semantic-knowledge-extraction
PS C:\Users\amlal\Desktop\OpenAI-PRoject\SK-Demo\semantic-kernel-main\semantic-kernel-main> pip install PyGithub
Collecting PyGithub
  Obtaining dependency information for PyGithub from https://files.pythonhosted.org/packages/2c/71/aff5465d9e3d448a5d4beab1dc7c8dec72037e3ae7e0d856ee08538dc934/PyGithub-1.59.1-py3-none-any.whl.metadata
  Downloading PyGithub-1.59.1-py3-none-any.whl.metadata (2.0 kB)
Collecting deprecated (from PyGithub)
  Obtaining dependency information for deprecated from https://files.pythonhosted.org/packages/20/8d/778b7d51b981a96554f29136cd59ca7880bf58094338085bcf2a979a0e6a/Deprecated-1.2.14-py2.py3-none-any.whl.metadata
  Downloading Deprecated-1.2.14-py2.py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: pyjwt[crypto]>=2.4.0 in c:\python311\lib\site-packages (from PyGithub) (2.7.0)
Collecting pynacl>=1.4.0 (from PyGithub)
  Downloading PyNaCl-1.5.0-cp36-abi3-win_amd64.whl (212 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 212.1/212.1 kB 517.7 kB/s eta 0:00:00
Requirement already satisfied: requests>=2.14.0 in c:\python311\lib\site-packages (from PyGithub) (2.31.0)
Requirement already satisfied: cryptography>=3.4.0 in c:\python311\lib\site-packages (from pyjwt[crypto]>=2.4.0->PyGithub) (41.0.1)
Requirement already satisfied: cffi>=1.4.1 in c:\python311\lib\site-packages (from pynacl>=1.4.0->PyGithub) (1.15.1)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\python311\lib\site-packages (from requests>=2.14.0->PyGithub) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in c:\python311\lib\site-packages (from requests>=2.14.0->PyGithub) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\python311\lib\site-packages (from requests>=2.14.0->PyGithub) (2.0.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\python311\lib\site-packages (from requests>=2.14.0->PyGithub) (2023.5.7)
Collecting wrapt<2,>=1.10 (from deprecated->PyGithub)
  Downloading wrapt-1.15.0-cp311-cp311-win_amd64.whl (36 kB)
Requirement already satisfied: pycparser in c:\python311\lib\site-packages (from cffi>=1.4.1->pynacl>=1.4.0->PyGithub) (2.21)
Downloading PyGithub-1.59.1-py3-none-any.whl (342 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 342.2/342.2 kB 559.7 kB/s eta 0:00:00
Downloading Deprecated-1.2.14-py2.py3-none-any.whl (9.6 kB)
Installing collected packages: wrapt, pynacl, deprecated, PyGithub
Successfully installed PyGithub-1.59.1 deprecated-1.2.14 pynacl-1.5.0 wrapt-1.15.0
PS C:\Users\amlal\Desktop\OpenAI-PRoject\SK-Demo\semantic-kernel-main\semantic-kernel-main> pip install azure-semantic-knowledge-extraction
ERROR: Could not find a version that satisfies the requirement azure-semantic-knowledge-extraction (from versions: none)
ERROR: No matching distribution found for azure-semantic-knowledge-extraction
PS C:\Users\amlal\Desktop\OpenAI-PRoject\SK-Demo\semantic-kernel-main\semantic-kernel-main> pip install azure-semantic-knowledge-extraction[github]
ERROR: Could not find a version that satisfies the requirement azure-semantic-knowledge-extraction[github] (from versions: none)
ERROR: No matching distribution found for azure-semantic-knowledge-extraction[github]
PS C:\Users\amlal\Desktop\OpenAI-PRoject\SK-Demo\semantic-kernel-main\semantic-kernel-main> `

**Comment by gitri-ms** [comment]
@amitlals - unfortunately it looks like the Github sample is not supported with the Python version of KernelHttpServer, as there is not currently an implementation of the Github skill for Python. (reference: #915) 

@shawncal @awharrison-28 Can you comment if we are planning to add support for the remaining sample apps? At a minimum, we should update the READMEs to be clearer about which ones are/aren't supported for Python.

**Comment by gitri-ms** [comment]
For the second issue -- the first page we ask you to choose a completion model and the second page we ask for embedding model. You're seeing the error because you have an embedding model selected for completion. Are any completion models showing in the dropdown? (e.g. gpt-4, gpt-3.5-turbo)

**Comment by amitlals** [comment]
> @amitlals - unfortunately it looks like the Github sample is not supported with the Python version of KernelHttpServer, as there is not currently an implementation of the Github skill for Python. (reference: #915)
> 
> @shawncal @awharrison-28 Can you comment if we are planning to add support for the remaining sample apps? At a minimum, we should update the READMEs to be clearer about which ones are/aren't supported for Python.

@gitri-ms Thanks for the update! I'll try DotNet flavor, please update the documentation accordingly.

**Comment by amitlals** [comment]
> 
I believe its might be happening due to no package picked up due to KernelHttpServer is not having base packages. Error was showing for ALL openAI packages from my OpenAI API

**Comment by teresaqhoang** [comment]
> Appreciate your inputs. Is it possible I trigger KernelHttpServer in DotNet and run yarn in python? Before I try I'd like to get confirmation. Thanks!! @gitri-ms @shawncal

The sample apps are built on TypeScript, so python should not matter here. Just make sure you're in the `samples\apps\github-qna-webapp-react` folder and you can run yarn

Hope this helps!

**Comment by matthewbolanos** [comment]
We have decided that we will be deprecating the existing web samples in favor of the samples on learn.microsoft.com. We tracking the work here: https://github.com/microsoft/semantic-kernel/issues/2810 , so we'll be closing out issues related to these samples.
