### ISSUE TITLE
CompleteRequestSettings is insufficiently abstract

### ISSUE THREAD

**Issue by douglasware** [microsoft/semantic-kernel#2735]
Note: I could also file this as a bug as many models do not work with SK and the Oobabooga and HuggingFace connectors because of this problem.

When I started using other completion APIs, e.g. Oobabooga, HuggingFace, the design around Microsoft.SemanticKernel.AI.TextCompletion.CompleteRequestSettings gets inconvenient quickly because behind those APIs the parameters vary, and the SK implementation is specifically shaped around OpenAI API. 

Seems like this one design element is a big blocker to the vision of a pluggable system.

A simple (but not terribly robust) solution would be to get rid of CompleteRequestSettings altogether and allow the use of a name/value collection instead.

**Comment by sammiie** [comment]
To address the issue of CompleteRequestSettings being insufficiently abstract and not accommodating different completion APIs (such as Oobabooga and HuggingFace), you can implement a more flexible and extensible design using a name/value collection. Below is a structured explanation, along with a diagram, to illustrate how this can be achieved:

Issue Explanation:

The CompleteRequestSettings class in Microsoft.SemanticKernel.AI.TextCompletion is tightly coupled with the OpenAI API and does not provide a generic way to accommodate various completion APIs, causing inconvenience and a lack of flexibility.

Solution: Flexible Request Settings with Name/Value Collection

1. Introducing RequestSettings Collection:

Create a new RequestSettings collection that is based on a name/value pair structure. This collection will serve as a generic container for request parameters.
2. Decoupling Request Settings:

Modify the code to decouple request settings from a specific API. Instead of having a dedicated class for each API (e.g., OpenAIRequestSettings, OobaboogaRequestSettings, HuggingFaceRequestSettings), use the generic RequestSettings collection.
3. Dynamic Configuration:

Allow developers to dynamically configure request parameters by adding or modifying name/value pairs within the RequestSettings collection.
4. Adapters for Specific APIs:

Implement separate adapter classes for each API (e.g., OpenAIAdapter, OobaboogaAdapter, HuggingFaceAdapter). These adapters will interpret the generic RequestSettings and convert them into API-specific parameters.
5. Diagram Structure:

Create a diagram to illustrate the revised architecture with the RequestSettings collection and API-specific adapters.
Here's a simplified diagram structure to explain the concept:

sql

+---------------------------------------------------+
|                   Application Code                |
|                                                 |
|    +---------------+         +-----------------+  |
|    | Request       |         | API-Specific   |  |
|    | Settings      | ------->| Adapter         |  |
|    | Collection    |         | (OpenAI,        |  |
|    | (Name/Value   |         | Oobabooga,      |  |
|    |  Pairs)       |         | HuggingFace,    |  |
|    +---------------+         | etc.)           |  |
|                                                 |
|    +---------------+                             |
|    | Completion    |                             |
|    | Engine        |                             |
|    | (Common Code) |                             |
|    +---------------+                             |
|                                                 |
|                                                 |
|    +---------------+                             |
|    | Request       |                             |
|    | Settings      |                             |
|    | Collection    |                             |
|    | (Name/Value   |                             |
|    |  Pairs)       |                             |
|    +---------------+                             |
|                                                 |
+---------------------------------------------------+
In this diagram:

The "Application Code" configures request settings using the RequestSettings collection.
The "API-Specific Adapter" is responsible for translating generic RequestSettings into API-specific parameters.
The "Completion Engine" remains agnostic to the specific API, as it only interacts with the generic RequestSettings collection.
With this design, you can easily accommodate different completion APIs by adding new adapters for each API while maintaining a consistent and flexible request parameter system. Developers can configure request settings dynamically using the name/value pairs within the RequestSettings collection, enabling a pluggable and extensible system.

**Comment by douglasware** [comment]
I've added support for Function Calling in my fork this week and it's pretty obvious that the library painted itself into a corner here with ChatRequestSettings, CompleteRequestSettings, and ISKFunction. You are going to be forced to do a big refactor soon and break some stuff. 

Is there a branch I can watch to follow along?

**Comment by markwallace-microsoft** [comment]
@douglasware I'll a link to the PR once I have something to share. I expect to have something later this week.

**Comment by markwallace-microsoft** [comment]
@douglasware Here's the PR https://github.com/microsoft/semantic-kernel/pull/2829. I still have more testing to do but any feedback is much appreciated.

**Comment by markwallace-microsoft** [comment]
@douglasware Could you take a look at this comment https://github.com/microsoft/semantic-kernel/pull/2829#discussion_r1329960229 to see does this change make sense
