### ISSUE TITLE
Using Azure OpenAI for the GitHub repo sample gives errors

### ISSUE THREAD

**Issue by anirudhgarg** [microsoft/semantic-kernel#275]
When trying to use Azure OpenAI for the GitHub repo example I get an error saying the particular model is not available. 

To Reproduce
1. Go to 'Completion Model" tab in the GitHub repo bot example
2. Click on Azure OpenAI
3. Enter the Azure OpenAI Key and the Endpoint
4. It correctly goes and is able to enumerate the model names. 
5. However on selecting a model and clicking Save gives the following error
7. See error
![image](https://user-images.githubusercontent.com/1995534/229371889-b3eb418f-9c4c-4698-a899-d25f3bd2ef66.png)

**Expected behavior**
Expected behavior is that this works.  Btw this example works fine when using OpenAI key.

**Additional context**
It appears to me that somehow it is looking for the wrong name of the model.  Also I did check that I am able to use the model successfully from within the Azure OpenAI service itself. I also waited for several hours to make sure that the model was successfully deployed in the Azure OpenAI service.

**Comment by anirudhgarg** [comment]
Also the Chat Summary App works fine with Azure OpenAI with the same parameters as above.

**Comment by dluc** [comment]
@craigomatic

**Comment by craigomatic** [comment]
I believe this is due to the samples currently expecting text completion endpoints, not chat completion endpoints (which 3.5 turbo and 4 require). 

We added additional validation to the github sample that does not exist in the prior chat sample which may explain that discrepancy - I expect it to fail there also. 

Do you have davinci-003 available to try?

**Comment by mahomedalid** [comment]
I actually had this error myself today, in both completion and embedding steps. I found out that my **deployment** needs to be named **exactly** the same as the **model** in order to get it working. I think I can get it to replicate again, just create a model deployment with a different name than the model name.

**Comment by evchaki** [comment]
Glad this is working
