### ISSUE TITLE
.Net: OpenAI function calling - enable auto execution of functions

### ISSUE THREAD

**Issue by gitri-ms** [microsoft/semantic-kernel#2932]
Expand on our function calling support to enable the kernel to automatically execute functions returned by the model. This needs further consideration on questions such as:
- how to maintain separation between connector-specific constructs and the core kernel abstractions
- how to differentiate between chat message results and function results
- how this impacts flows/chaining

For context, the initial implementations of function calling (and some discussion on this topic) are here: #2842 & #2356

**Comment by stephentoub** [comment]
I left a few comments at https://github.com/microsoft/semantic-kernel/pull/2842#discussion_r1353907112, but FWIW, I think this is a key differentiator that SK can provide. It takes something that's otherwise filled with boilerplate and leverages SK's strengths and the knowledge already built up to reduce that boilerplate all down to a one-liner. We should make this happen :)

**Comment by stephentoub** [comment]
Here's approximately what I think we should do for v1:
https://github.com/microsoft/semantic-kernel/compare/main...stephentoub:semantic-kernel:chatcompletionwithfunctions

This is adding an `IChatCompletionWithFunctions`, which exposes a `GetChatCompletionsAsync` and `GetStreamingChatCompletionsAsync` that just takes an additional argument (in my commit, it's an `SKContext`, but it could be something else that includes functions).  This makes it trivial for a consumer to just do the normal chatting but with planning integrated into the chat: in the case of OpenAI or Azure OpenAI, the implementation can choose to use the server-side functionality, or in the case of another provider, it could choose to use a client-side planner and proactively augment the chat information sent.

The difference in what consumption like is night and day.  Take a look at the `Example59_OpenAIFunctionCalling`.  There are four implementations there: automatic (using this new interface) vs manual (working at the message level directly), and non-streaming vs streaming.  The automatic ones that leverage IChatCompletionWithFunctions make it a no-brainer to use. The manual ones are not only incredibly hard (and not all that much better than what you can do at the underlying OpenAIClient level), you can't even implement the manual streaming one today due to missing support in SK.

I would strongly urge us to make getting something like this in for 1.0 a priority.
