### ISSUE TITLE
.Net: Token usage on all interactions with SK where LLM is engaged

### ISSUE THREAD

**Issue by arynaq** [microsoft/semantic-kernel#2987]
First of all, great library and amazing work you guys put here. I have full respect that this space is very fast moving so probably something you have considered but it would be very nice to differentiate between:

1. "You can use components directly, such as AzureChatCompletion if you want full control"
2. "But if you let the kernel manage this, you will get this out of the box" where "this" at least contains the total token usage, what models were involved, general observability metrics that are relevant for the business context (and not necessarily purely technical).

The above is relevant if you consider this 

```c#
var kernel = new KernelBuilder()
        .WithAzureChatCompletionService(deploymentName: _options.Deployment, endpoint: _options.Endpoint, apiKey: _options.ApiKey)
        .Build();

        var context = kernel.CreateNewContext();
        context.Variables["input"] = request.Note;

        var promptConfig = new PromptTemplateConfig
        {
            Completion = new PromptTemplateConfig.CompletionConfig { MaxTokens = 1000, Temperature = 0 }
        };
        var promptTemplate = new PromptTemplate(prompt, promptConfig, kernel);
        var final_prompt = await promptTemplate.RenderAsync(context, cancellationToken: cancellationToken);
        var completion = new AzureChatCompletion(modelId: _options.Deployment, endpoint: _options.Endpoint, apiKey: _options.ApiKey);
        var messages = completion.CompleteStreamAsync(final_prompt, new CompleteRequestSettings { MaxTokens = 1000, Temperature = 0 }, cancellationToken: cancellationToken);
        
        await foreach (string message in messages)
        {
            yield return message;
        }
```

I feel like I am bypassing the entire kernel just to be able to use the streaming capability of the underlying integration with the LLM, so I miss out on getting info on token usage.

Am I following an anti-pattern here, could I somehow leverage the SK and its context to do the work above so I can get info on token usage?

**Comment by dmytrostruk** [comment]
Hi @arynaq ! Thanks for great feedback!

We encourage to integrate with LLMs via Kernel instance, because it provides more features out of the box, than using some specific module directly.

Streaming capability via Kernel is currently under development: https://github.com/microsoft/semantic-kernel/pull/2986.

We have a couple of ways how to observe token usage.

### Telemetry Host
It's possible to configure telemetry host for Kernel as well as separate module, like `AzureChatCompletion`.

Here is an example how to configure Application Insights telemetry:
https://github.com/microsoft/semantic-kernel/blob/main/dotnet/samples/ApplicationInsightsExample/Program.cs

This document contains list of available metrics (including metrics for tokens - `SK.Connectors.OpenAI.PromptTokens`, `SK.Connectors.OpenAI.CompletionTokens`, `SK.Connectors.OpenAI.TotalTokens`):
https://github.com/microsoft/semantic-kernel/blob/main/dotnet/docs/TELEMETRY.md

### Model Results

This example shows how to get token usage when using Kernel and ChatCompletion directly:
https://github.com/microsoft/semantic-kernel/blob/main/dotnet/samples/KernelSyntaxExamples/Example43_GetModelResult.cs

### Pre/Post Hooks

Pre/Post hooks are available only when using Kernel instance:
https://github.com/microsoft/semantic-kernel/blob/main/dotnet/samples/KernelSyntaxExamples/Example57_FunctionEventHandlers.cs

---

Although, as far as I can see, there is no token information in Azure SDK when using streaming methods, looks like it's only available for non-streaming methods. One possible way would be to use one of the available C# tokenizers and count prompt/completion tokens on your side. 

Please, let me know if this information is helpful. Thank you!

**Comment by arynaq** [comment]
Thanks for the information @dmytrostruk!

Looks like modelresult is just what I need in this case and looking forward to getting my claws on #2986. The telemetry hooks are nice for dashboards :)
