### ISSUE TITLE
.Net: Function calling: Update ChatMessage to support 'name'

### ISSUE THREAD

**Issue by gitri-ms** [microsoft/semantic-kernel#3017]
> [!IMPORTANT]  
> Labeled **Urgent** because it may require a breaking change. Please reduce the priority if this is not the case.

To fully support the function calling RAG pattern, we need to have a "name" field in our chat message objects. However, there are concerns about putting OpenAI specific fields in abstraction classes, so this may require a refactor of the chat message abstraction.
Here's an example of adding the "name" field to enable the full function calling scenario: https://github.com/gitri-ms/semantic-kernel/pull/2

**Comment by stephentoub** [comment]
If we're not comfortable adding a name property to a chat message in support of this, we could also just add a dictionary to the message so that additional context can be provided and interpreted by the chat completion service however it likes:
https://github.com/microsoft/semantic-kernel/compare/main...stephentoub:semantic-kernel:fixfunctioncalling

We need to do something here, whatever approach we pick. As it stands, the feature that's merged isn't actually usable as-is, since there's no way to send the function result back to the LLM.

**Comment by matthewbolanos** [comment]
Our min bar for getting function calling done for v1.0.0 is to make sure that it can be used by Stepwise planner.

**Comment by leungkimming** [comment]
I agree with Stephen. In my use case, my prompt will trigger multiple functions. I need to return the function results to LLM for it to compile the final reply consisting of all the function call results. I don't want to fallback to native OpenAI API calls.

**Comment by leungkimming** [comment]
> Important Labeled **Urgent** because it may require a breaking change. Please reduce the priority if this is not the case.
> 
> To fully support the function calling RAG pattern, we need to have "name" and "function_call" fields in our chat message objects. However, there are concerns about putting OpenAI specific fields in abstraction classes, so this may require a refactor of the chat message abstraction. Here's an example of adding the "name" field to enable the full function calling scenario: [gitri-ms#2](https://github.com/gitri-ms/semantic-kernel/pull/2)

@gitri-ms, I have tested your solution and found an issue. I have a CheckStock function and my prompt is "How many tables and chairs are ther in stock?". Note that LLM should issue 2 function calling messages (I have added a do-while loop in Example59). However, with your version, LLM only call CheckStock once. In my original working version using native OpenAI, the Messages in the ChatCompletionsOptions keeps both the function calling assistance message and the function return user message. In your solution, only function return user 
messages were kept in the abstracted ChatMessageBase. Hence, in ClientBase.cs, when CreateChatCompletionsOptions populate ChatCompletionsOptions using the abstracted ChatMessageBase, there are no function calling assistance message histories passing back to the LLM.

Since this enhancement is already in the in-progress sprint, please take this into consideration.

**Comment by markwallace-microsoft** [comment]
PR https://github.com/microsoft/semantic-kernel/pull/3302
