### ISSUE TITLE
.Net: Creating Semantic Function doesnt parse paramers

### ISSUE THREAD

**Issue by colombod** [microsoft/semantic-kernel#3115]
**Describe the bug**
Creating a semantic function with a prompt template with parameters does not return the parameter list

**To Reproduce**
this code
```csharp
 var function = _semanticKernel.CreateSemanticFunction(
     """
      {{$input}}

      Summarize the text above in the style of {{$person}}.
     """,
     "summarize");

var parameters = function.Describe().Parameters.Select(p => p.Name).ToArray();

```

used to produce 2 values, with version 1.0.0-Beta1 this is always producing an empty array

**Expected behavior**
Should return 2 parameters

**Screenshots**

**Platform**
 - OS: [e.g. Windows, Mac]
 - IDE: [e.g. Visual Studio, VS Code]
 - Language: C#
 - Source:  NuGet package version 1.0.0-beta1

**Additional context**

**Comment by markwallace-microsoft** [comment]
We changed `IPromptTemplateEngine` to remove the method `ExtractBlocks` because it wasn't very generic and would not be easy to support for more advanced template engines e.g. Handlebars or Razor. This removed the ability to be able to extract the variable names from a template and hence this issue. At the time we considered adding a method `IPromptTemplateEngine.GetVariableNames` but decided against this as there wasn't a compelling use case. This could be the use case we need to justify adding this back. @matthewbolanos what's your opinion?

**Comment by matthewbolanos** [comment]
To support other template engines, we will be removing this functionality. Instead, developers will need to explicitly define the inputs to their semantic functions.
