### ISSUE TITLE
.Net: After upgrade to 1.0, InvokeAsync returns FunctionResult with no way to get SKContext?

### ISSUE THREAD

**Issue by wrharper-AASP** [microsoft/semantic-kernel#3120]
![image](https://github.com/microsoft/semantic-kernel/assets/117128832/eac18f1e-3f55-4327-a067-c331d292bea5)
Shouldn't this be public? How do you get the SKContext or a ToString with this new way as of 1.0 beta now?

**Comment by wrharper-AASP** [comment]
This is needed because of my token encoder:
How it was: SKContext result = await chatFunction.InvokeAsync(context);
tikToken.EncodeCount(result.ToString())

New way: FunctionResult fresult = await chatFunction.InvokeAsync(context);
tikToken.EncodeCount(fresult.?????)

**Comment by wrharper-AASP** [comment]
Context should be public because then it would be possible to do:
New way: SKContext result = (await chatFunction.InvokeAsync(context)).Context;
tikToken.EncodeCount(result.ToString())
and things would still work....

**Comment by wrharper-AASP** [comment]
Alternatively, create a (await chatFunction.InvokeAsync(context)).GetTokenCount or something like that?

chatFunction is a ISKFunction

**Comment by wrharper-AASP** [comment]
also, what's up with this?
var semanticFunc = kernel.CreateSemanticFunction(message + memorySearch);
//var result = await semanticFunc.InvokeAsync();
var fresult = await semanticFunc.InvokeAsync(kernel);
Why can't you just keep it await semanticFunc.InvokeAsync(); ??? it should just use its own kernel that it is called from?

**Comment by dmytrostruk** [comment]
Hi @wrharper-AASP !

In case your `chatFunction` returns string, then you can access your result as:
```csharp
FunctionResult fresult = await chatFunction.InvokeAsync(context);
tikToken.EncodeCount(fresult.GetValue<string>());
```

`SKContext` as a result type was replaced with `FunctionResult` in case you invoke function directly or `KernelResult` in case you invoke function through Kernel instance.

A couple of reasons for that:
- We started to see some patterns of `SKContext` usage which is different from initial `SKContext` purpose. That's why we try to make it as internal mechanism rather than public input/output object.
- `SKContext` supports only `string` as return data type. With `FunctionResult`, you can access not only strings, but any kind of data, including complex types as well as streaming (`IAsyncEnumerable<T>`).

By following link, you can find ADR with more details about this change:
https://github.com/microsoft/semantic-kernel/blob/main/docs/decisions/0009-function-and-kernel-result-types.md

**Comment by dmytrostruk** [comment]
> Alternatively,
> create a int (await chatFunction.InvokeAsync(context)).TokenCount?

@wrharper-AASP Regarding token information:

We have a couple of ways how to observe token usage.

### Telemetry Host
It's possible to configure telemetry host for Kernel as well as separate module, like `AzureChatCompletion`.

Here is an example how to configure Application Insights telemetry:
https://github.com/microsoft/semantic-kernel/blob/main/dotnet/samples/ApplicationInsightsExample/Program.cs

This document contains list of available metrics (including metrics for tokens - `SK.Connectors.OpenAI.PromptTokens`, `SK.Connectors.OpenAI.CompletionTokens`, `SK.Connectors.OpenAI.TotalTokens`):
https://github.com/microsoft/semantic-kernel/blob/main/dotnet/docs/TELEMETRY.md

### Model Results

This example shows how to get token usage when using Kernel and ChatCompletion directly:
https://github.com/microsoft/semantic-kernel/blob/main/dotnet/samples/KernelSyntaxExamples/Example43_GetModelResult.cs

### Pre/Post Hooks

Pre/Post hooks are available only when running function through Kernel instance:
https://github.com/microsoft/semantic-kernel/blob/main/dotnet/samples/KernelSyntaxExamples/Example57_FunctionEventHandlers.cs

**Comment by wrharper-AASP** [comment]
> > var fresult = await semanticFunc.InvokeAsync(kernel);
> > Why can't you just keep it await semanticFunc.InvokeAsync(); ??? it should just use its own kernel that it is called from?
> 
> @wrharper-AASP At the moment, `SKContext` is required input parameter for `ISKFunction`.
> 
> Available options:
> 
> * Pass context as input parameter: `function.InvokeAsync(context)`.
> * Pass kernel as input parameter: `function.InvokeAsync(kernel)`. This is just extension method, which internally will do first option in following way: `function.InvokeAsync(kernel.CreateNewContext(...))`.
> 
> But in general, we recommend running your functions through Kernel instance. Kernel will act as function orchestrator and will pass information from one function to another, if you have multiple functions in pipeline. It will also provide an ability to use function Pre/Post Hooks, which will give you more control over function execution.
> 
> Example with Pre/Post Hooks: https://github.com/microsoft/semantic-kernel/blob/main/dotnet/samples/KernelSyntaxExamples/Example57_FunctionEventHandlers.cs

then what did function.invokeasync() originally do? I need to be able to do that still... what is the equivalent to the same result?

**Comment by wrharper-AASP** [comment]
> > Alternatively,
> > create a int (await chatFunction.InvokeAsync(context)).TokenCount?
> 
> @wrharper-AASP Regarding token information:
> 
> We have a couple of ways how to observe token usage.
> 
> ### Telemetry Host
> It's possible to configure telemetry host for Kernel as well as separate module, like `AzureChatCompletion`.
> 
> Here is an example how to configure Application Insights telemetry: https://github.com/microsoft/semantic-kernel/blob/main/dotnet/samples/ApplicationInsightsExample/Program.cs
> 
> This document contains list of available metrics (including metrics for tokens - `SK.Connectors.OpenAI.PromptTokens`, `SK.Connectors.OpenAI.CompletionTokens`, `SK.Connectors.OpenAI.TotalTokens`): https://github.com/microsoft/semantic-kernel/blob/main/dotnet/docs/TELEMETRY.md
> 
> ### Model Results
> This example shows how to get token usage when using Kernel and ChatCompletion directly: https://github.com/microsoft/semantic-kernel/blob/main/dotnet/samples/KernelSyntaxExamples/Example43_GetModelResult.cs
> 
> ### Pre/Post Hooks
> Pre/Post hooks are available only when running function through Kernel instance: https://github.com/microsoft/semantic-kernel/blob/main/dotnet/samples/KernelSyntaxExamples/Example57_FunctionEventHandlers.cs

This is way worse than my use case. I created a custom .net 6 tiktoken that is like pythons. I definitely will be using that instead of these options.

**Comment by wrharper-AASP** [comment]
I will give an example of my use case for tokens and why these examples can't go to this level of detail:

```
                var semanticFunc = kernel.CreateSemanticFunction(message + memorySearch);
                var result = await semanticFunc.InvokeAsync();
                string sResult = result.ToString() + Environment.NewLine + Environment.NewLine;
                sResult += "Tokens message request: " + tikToken.EncodeCount(message) + Environment.NewLine;
                sResult += "Extra message tokens needed to query the memory search results: " + tikToken.EncodeCount(memorySearch) + Environment.NewLine;
                sResult += "Total message tokens: " + tikToken.EncodeCount(message + memorySearch) + Environment.NewLine;
                sResult += "Completition tokens: " + tikToken.EncodeCount(sResult) + Environment.NewLine;
                sResult += "Total tokens: " + tikToken.EncodeCount(sResult + message + memorySearch);
                return sResult;
```

this way token information is presented at the bottom but not really saved. It is just extra temporary info, and I can get the details for each piece of exactly what is going on.

I'm sorry but this upgrade seems like a massive downgrade for me to me so far.

**Comment by dmytrostruk** [comment]
> then what did function.invokeasync() originally do? I need to be able to do that still...

Internally, `function.InvokeAsync()` without parameters created new SKContext object:
![image](https://github.com/microsoft/semantic-kernel/assets/13853051/5ba0b539-396c-4f83-9eb8-1c92c90a584f)

We removed the possibility to initialize `SKContext` object on user side, because, as I mentioned in previous comments, `SKContext` at some point will become internal mechanism only. We think that instead of working with SKContext object and string only, users need to be able to work with any kind of parameters and return types in their functions, including complex types and streaming. These changes are initial steps to improve data handling between different functions.


> what is the equivalent to the same result?

As mentioned in previous comment, the available options are:
- Pass context as input parameter: `function.InvokeAsync(context)`.
- Pass kernel as input parameter: `function.InvokeAsync(kernel)`.

In order to create new context, you can use `kernel.CreateNewContext(...);`. But it's not a recommended approach. Ideally, the function should be executed through Kernel instance: `kernel.RunAsync(function);`


> this way token information is presented at the bottom but not really saved. It is just extra temporary info, and I can get the details for each piece of exactly what is going on.

If you want more control over token counting, it's always possible to use your own tokenization logic. This scenario was not changed in `1.0.0-beta1`.
We also have an example with 4 different available .NET tokenizers:
https://github.com/microsoft/semantic-kernel/blob/main/dotnet/samples/KernelSyntaxExamples/Example55_TextChunker.cs


> I'm sorry but this upgrade seems like a massive downgrade to me so far.

I'm sorry to hear that your experience with new version did not exceed your expectations. We are here to support you in migration process. 
All previous scenarios are still supported. Some of them can be achieved with slightly different syntax. With recent changes we are trying to make some space for future improvements to make SK even better. Sorry for any inconvenience.

**Comment by wrharper-AASP** [comment]
kernel.RunAsync(function); is a new one I have not ran yet.
the problem i have with
 fresult.GetValue<string>()
 vs
SKContext result = await chatFunction.InvokeAsync(context);
tikToken.EncodeCount(result.ToString())
is will it get everything in the current ISK or just the response from the AI? Will the results actually be the same?

**Comment by dmytrostruk** [comment]
> will it get everything in the current ISK or just the response from the AI? Will the results actually be the same?

If your `chatFunction` is Semantic Function, then `fresult.GetValue<string>()` will return the same result as previous `context.ToString()`. On top of that, `FunctionResult` also contains `Metadata` property, which may contain some useful information about function execution (e.g. Response from AI, token count etc).

In next release we will deliver `ToString` override to `FunctionResult`, so in your case it will be possible to do:
```csharp
FunctionResult result = await chatFunction.InvokeAsync(context);
tikToken.EncodeCount(result.ToString())
```

And if your `chatFunction` returns string internally, then `ToString` will return the same result. Please, let me know if this would simplify the usage for you. Thanks a lot!

**Comment by wrharper-AASP** [comment]
That is very helpful, it will keep consistency and still allow the upgrade for those who wish to do the new features you guys are creating! I guess that is what I was trying to say. This makes things clearer.
