### ISSUE TITLE
.Net: Kernel.RunAsync() remove legacy call patterns (including params)

### ISSUE THREAD

**Issue by matthewbolanos** [microsoft/semantic-kernel#3143]
> [!IMPORTANT]  
> Labeled **Urgent** because it will require a breaking change.

**Comment by matthewbolanos** [comment]
Per #3145 

> should no longer expose the “params” version where a list of functions is passed in
> This is a very limited call pattern as it does not accept args on functions, and is no longer be recommended (though the samples still showcase this).
> If shorthand for plan creation is still needed, an alternative call pattern can be built that feels more natural to dotnet developers

**Comment by shanselman** [comment]
FYI https://github.com/microsoft/semantic-kernel/blob/main/dotnet/README.md the basic sample doesn't work anymore because the nice clear RunAsync(string) now wants a Microsoft.SemanticKernel.Orchestration.SKContext. Not sure why SK is needed as a type prefix when the large namespace handles scoping for you, or why this internal type is exposed at all. 

During this refactor, what is the clean "hello world" for .NET? This was clear (like Python's is). 

I'd encourage us to not forget the '5 lines to wow' crowd as you refactor for the enterprise.

(this no longer works, as you know)
```
var summarize = kernel.CreateSemanticFunction(prompt);
string text1 = @"how are you";
Console.WriteLine(await summarize.InvokeAsync(text1));
```

**Comment by markwallace-microsoft** [comment]
We have these new "Getting Started" samples which show simplex things are easy and advanced scenarios are supported with very little extra code

https://github.com/microsoft/semantic-kernel/blob/main/dotnet/samples/KernelSyntaxExamples/Getting_Started/Step1_Create_Kernel.cs
https://github.com/microsoft/semantic-kernel/blob/main/dotnet/samples/KernelSyntaxExamples/Getting_Started/Step2_Add_Plugins.cs
