### ISSUE TITLE
.Net: MinHeap and TopNCollection should not be public

### ISSUE THREAD

**Issue by stephentoub** [microsoft/semantic-kernel#3152]
> [!IMPORTANT]  
> Labeled **Urgent** because it may require a breaking change.

https://github.com/microsoft/semantic-kernel/issues/615 was closed as completed with (I thought) the resolution to make MinHeap internal, but in the latest release it's still public.  Both it and TopNCollection aren't something that are really in the domain of SK: a developer can use `PriorityQueue<>` in .NET, or `OrderBy(...).Take(...)`, or any number of other solutions if they need the equivalent.

**Comment by dmytrostruk** [comment]
@stephentoub We moved them to separate package `Microsoft.SemanticKernel.Plugins.Memory` and made them public as part of this package. One of the reasons is to be able to write some unit tests in separate test package. Otherwise, we will need to add `InternalsVisibleTo` attribute, and I'm not sure it's a good practice for testing internal classes/structures.

Do you have any recommendations here?

**Comment by stephentoub** [comment]
What are the unit tests doing with MinHeap/TopNCollection that they can't do with PriorityQueue, OrderBy.Take, etc.?

**Comment by dmytrostruk** [comment]
> What are the unit tests doing with MinHeap/TopNCollection that they can't do with PriorityQueue, OrderBy.Take, etc.?

Sorry, I meant unit tests for actual MinHeap/TopNCollection types :)
https://github.com/microsoft/semantic-kernel/blob/main/dotnet/src/Plugins/Plugins.UnitTests/Memory/Collections/MinHeapTests.cs
https://github.com/microsoft/semantic-kernel/blob/main/dotnet/src/Plugins/Plugins.UnitTests/Memory/Collections/TopNCollectionTests.cs

`TopNCollecton` is used in `VolatileMemoryStore` - our in-memory store implementation. Since `Plugins.Memory` package is based on `.NET Standard 2.0`, `PriorityQueue` is unavailable, unless we copy all its source code and place it in our repository.

**Comment by dmytrostruk** [comment]
Makes sense, thank you! Will use `InternalsVisibleTo` flag then.
