### ISSUE TITLE
.Net: Why is OpenAIRequestSettings.FunctionCall needed?

### ISSUE THREAD

**Issue by stephentoub** [microsoft/semantic-kernel#3181]
OpenAIRequestSettings has both:
```C#
    public string? FunctionCall { get; set; } = null;
    public IList<OpenAIFunction>? Functions { get; set; } = null;
```
and the docs state that FunctionCall can be set to "none" (don't use any functions), "auto" (use all the functions), or the name of a specific function.

Why is FunctionCall needed at all?  It seems like:
- "none" can be achieved by just not setting Functions at all or by setting it to an empty collection
- "auto" can be achieved by populating Functions with all (and only) the functions you want made available
- a specific function can be achieved by populating Functions with just that one function

And if we get rid of FunctionCall, we can also get rid of FunctionCallAuto and FunctionCallNone.

**Comment by dmytrostruk** [comment]
@stephentoub I agree with you, it looks like with `Functions` parameter we can achieve 3 different behaviors. On the other side, I think this is something that could be done on OpenAI side first, so then we can follow the same pattern. Otherwise, shouldn't we just follow OpenAI API and expose available properties, so users will be able to decide how to set these properties based on their scenarios?

Also, I think there are some differences between "function name" and "auto", which can't be achieved with one function in collection. With "function name" you **force** model to use specific function, while with "auto" you let model to decide on its own whether to call a function or not, and it's based on prompt. So, even if you have one function in `Functions` collection, with "auto" mode there may be a situation, when it won't be called by the model. 

From the first sight, it doesn't look like controlling this behavior with additional property can be useful, but maybe there are some advanced workflows which require high level of flexibility. 

Found this conversation as well:
https://github.com/microsoft/semantic-kernel/pull/2842#discussion_r1327012887
![image](https://github.com/microsoft/semantic-kernel/assets/13853051/0bb8a69b-8139-4808-964b-ac5b912ffcc4)

**Comment by matthewbolanos** [comment]
An the triage call, @gitri-ms called out the scenario where this flag would be necessary...
- If you only have _one_ function, there would need to be a flag to say if the AI _must_ return a function call back or if it should be in auto mode.
