### ISSUE TITLE
.Net [ChatRoles] 2. Completion service (ChatCompletion / TextCompletion) selection by SemanticFunction

### ISSUE THREAD

**Issue by SergeyMenshykh** [microsoft/semantic-kernel#3256]
As an engineer working on SK,
I want to have a mechanism allowing semantic function to select either text or chat completion API/Connector for execution
So, text prompts are handled by text completion connectors
And chat prompts are handled by chat completion connectors
Or chat prompt handled by text completion connectors and the other way around for fallback scenarios

Scope:

1. Create ADR and present it to the team.
2. Collect feedback and implement the completion service selection functionality.
```[tasklist]
### Tasks
- [x] ADR
- [ ] Implement
```

**Comment by stekiri** [comment]
@dmytrostruk, I read the ADR and it seems that the described logic has not been implemented. A different logic seems to have been introduced in https://github.com/microsoft/semantic-kernel/pull/4085. Is the ADR obsolete?

I stumbled upon it in the following scenario:
- Custom service that implements both `IChatCompletionService` and `ITextGenerationService`.
- Chat completion implementation is chosen without taking into account the logic of the ADR.

**Comment by dmytrostruk** [comment]
@stekiri Thank you for this comment. You are correct, the ADR which we added previously is kind of obsolete, because later we decided to proceed with other approach, which wasn't described in the documentation. We created a new ADR that explains new approach and we updated status of previous ADR in this PR: https://github.com/microsoft/semantic-kernel/pull/5479

Do you have a specific scenario that is not covered by current approach?

**Comment by stekiri** [comment]
Yes, my scenario is when a service implements both `IChatCompletionService` and `ITextGenerationService`.

My reasoning would be:
If a user implements `ITextGenerationService` for a service, then the user made a conscious choice that he considers it being the important (and maybe better as chat completion?) for a given use case. Therefore, it should take precedence over `IChatCompletionService` if there is no chat in his prompt.

Some code is worth more than a thousand words, so I made this small [draft PR](https://github.com/microsoft/semantic-kernel/pull/5495) to communicate what I had in mind. My logic might be flawed, so maybe I miss some use cases that would not be supported with such a change.

**Comment by dmytrostruk** [comment]
> If a user implements `ITextGenerationService` for a service, then the user made a conscious choice that he considers it being important (and maybe better as chat completion?) for a given use case. Therefore, it should take precedence over `IChatCompletionService` if there is no chat in his prompt.

I think this scenario is supported, because user could place text generation logic in separate class and implement only `ITextGenerationService` interface. If user has some common logic for text generation and chat completion that should be re-used in both services, instead of implementing 2 interfaces in the same class, user could create 2 classes, implement both interfaces separately, and put common logic in base class. In order to be able to switch between different services, it's possible to create multiple kernel instances, where one of them will rely on text generation and another one on chat completion.

> Some code is worth more than a thousand words, so I made this small [draft PR](https://github.com/microsoft/semantic-kernel/pull/5495) to communicate what I had in mind. My logic might be flawed, so maybe I miss some use cases that would not be supported with such a change.

Thanks for the PR, it definitely helps to understand the idea. The scenario with fallback chat completion may work for now, but I think it will be hard to scale it as soon as we will add support for other types of services (image, audio etc). The solution with placing text generation and chat completion in separate classes should work as expected.
