### ISSUE TITLE
How can I see the prompt before it's sent to the model in native function?

### ISSUE THREAD

**Issue by DrEight** [microsoft/semantic-kernel#3349]
I've seen in the samples how I can see the prompt before it is sent to the model in the case of the semantic function, but I wasn't able to see it in the case of a native function.
How can I do that ?
In practice I would like to be able to see all the messages sent back and forward with the model. If I enable the logging I can only see the number of the tokens, but not the tokens and the content.

thanks

**Comment by matthewbolanos** [comment]
Are you able to share what prompt you're referring to in a _native_ function? Native functions likely/shouldn't have a prompt inside of it.

**Comment by DrEight** [comment]
probably I used to wrong term and 'prompt' is not correct. I'm assuming that a 'native function' is an OpenAI [function](https://platform.openai.com/docs/guides/function-calling).  What I would like to see is the body of the message sent to the model, to better understand how it works. I hope I made my self clear

**Comment by samleegithub** [comment]
Native function means it is a function that is using only code and not any LLM model calls.

Semantic functions uses prompts sent to a LLM model.

**Comment by DrEight** [comment]
Thank you for the clarification, this wasn't clear to me. So, if I understand correctly a native function is just a callback, right ?
Another question: how can I use the OpenAI function with the SK ?

**Comment by matthewbolanos** [comment]
Yes, native functions are just callbacks. The value of Semantic Kernel is to semantically describe these callbacks so that they can be passed to an LLM. In OpenAI's case, we allow these functions to be passed via the function calling feature so that OpenAI can tell Semantic Kernel to invoke the function.

I _think_ the question you have is how to see how the native function is being serialized before it is sent to OpenAI via function calling. Is this correct? If so, I don't think we have this exact thing today, but you should be able to get the function views using pre-hooks in Semantic Kernel.

**Comment by DrEight** [comment]
yes, you are correct: I would like to see how the functions are serialised. It is only for curiosity and to understand what it is happening behind the scene. I don't have a use case. Today I found this [blog post](https://devblogs.microsoft.com/semantic-kernel/introducing-v1-0-0-beta6-for-the-net-semantic-kernel-sdk/)  that it mentions function hooks. It is probably the same thing you described. Am I correct ?

**Comment by matthewbolanos** [comment]
Yes! Those are it. I'll go ahead and close this issue. Please reopen if the hooks don't work as expected.
