### ISSUE TITLE
Python: Track token usage on LLM interactions

### ISSUE THREAD

**Issue by bastbu** [microsoft/semantic-kernel#3369]
Similar to #2987, which discusses how to track token usage statistics when interacting with LLMs:

Are there any supported approaches for tracking token usage in SK Python? The [implementation in `OpenAIChatCompletion`](https://github.com/microsoft/semantic-kernel/blob/831ff8edf063487104ecca100817b3ee0a91b03d/python/semantic_kernel/connectors/ai/open_ai/services/open_ai_chat_completion.py#L76) indicates that this may not yet be supported.

What are the recommended ways to track the token usage in SK Python?

**Comment by meronz** [comment]
Does #3496 solve this? One could use the existing IKernel FunctionInvoked callbacks to get track the token usage.

**Comment by bastbu** [comment]
> Does #3496 solve this? One could use the existing IKernel FunctionInvoked callbacks to get track the token usage.

I don't think this addresses my need. As far as I can see the PR targets the .NET implementation of Semantic Kernel, my question is specifically around the Python Semantic Kernel implementation.

**Comment by eavanvalkenburg** [comment]
@bastbu the service classes (AzureChatCompletion, OpenAIChatCompletion, etc) record the token usage if returned by the API, where streaming does not return token usage, they are incremented by each call and you can access them by using `chat_completion.total_tokens` (or prompt_tokens, completion_tokens, assuming your service is named `chat_completion`), I will make a note to add this to one of the samples so that we can refer to it there.
