### ISSUE TITLE
.Net: Add Anthropic Support (I can contribute a PR for this)

### ISSUE THREAD

**Issue by glorious-beard** [microsoft/semantic-kernel#3462]
I use the Semantic Kernel (great toolkit, by the way) with both OpenAI and Anthropic at my startup and I'd like to contribute our AI connector for Claude back to the community

I have the connector implemented in my forked repo (https://github.com/glorious-beard/semantic-kernel) and I can create a PR if there's interest.

**Comment by matthewbolanos** [comment]
Yes! This would be very interesting. Please go ahead and create a PR and we can review it!

**Comment by zhangxd6** [comment]
I'd suggest to make the apis avaiable to extend the connectors so that community can maintain and develop the connectors parallel to this repo. For instance, I am interested in get Ollama connector to run my all my stack locally. Whill trying to get it on a sepearte repo by referenceing kernel nuget, only found out there are internal classes to follow the openai connenctor implementation. It will be good to make them available to public while MS focus on couple of major ones.

**Comment by markwallace-microsoft** [comment]
All .Net issues prior to 1-Dec-2023 are being closed. Please re-open, if this issue is still relevant to the .Net Semantic Kernel 1.x release. In the future all issues that are inactive for more than 90 days will be labelled as 'stale' and closed 14 days later.

**Comment by kimsey0** [comment]
This is still interesting to us. @glorious-beard hasn't responded in #3476, but if he's willing to split up the pull request to comply with [the feature branch ADR](https://github.com/microsoft/semantic-kernel/blob/main/docs/decisions/0031-feature-branch-strategy.md), that would be cool. Otherwise, we'll consider if we can contribute here.

**Comment by therealpaulgg** [comment]
Any updates on this? Looking into potentially integrating the Claude models into our usage of SK.

**Comment by therealpaulgg** [comment]
Looks like someone has started a new effort here. https://github.com/microsoft/semantic-kernel/issues/5690
