### ISSUE TITLE
.Net: SK Plan generation exception - invalid attribute character

### ISSUE THREAD

**Issue by brandonh-msft** [microsoft/semantic-kernel#3501]
**Describe the bug**
I don't get this reliably, but when running a plan multiple times (different inputs), I have occasionally run into an XML parse error: `invalid attribute character`

**To Reproduce**
1. Create a Sequential plan
2. Run the plan w/ some inputs
3. Continue running until error

**Expected behavior**
Based on what I've read of past issues, [plans should be done in JSON now](https://github.com/microsoft/semantic-kernel/issues/721#issuecomment-1536832082)? Not sure why we're creating XML, then.

**Screenshots**
![image](https://github.com/microsoft/semantic-kernel/assets/20270743/d389e049-ff25-4f80-b049-921948ab1ece)

**Platform**
 - OS: Windows
 - IDE: Visual Studio
 - Language: C#
 - Source: NuGet package version 1.0.0-beta6

**Additional context**
My plan has Text memory and directory-loaded functions (ImportFunctionsFromDirectory)

**Comment by matthewbolanos** [comment]
Thank you for reporting this issue. Because of the number of issues we've run into with XML generation by the sequential planner, we've built a new planner that avoids these problems. You can see the new [Handlebars planner here](https://devblogs.microsoft.com/semantic-kernel/semantic-kernels-ignite-release-beta8-for-the-net-sdk/#gen-4-generate-multi-step-plans-with-the-handlebars-planner).

Because we've introduced this new planner, we plan to deprecate the current sequential planner (because of challenges like the one you faced). Can you try the new Handlebars planner and see if you get similar/different errors? Please create a new issue if you do.
