### ISSUE TITLE
Revisit design of ChatHistory and ChatMessage

### ISSUE THREAD

**Issue by markwallace-microsoft** [microsoft/semantic-kernel#3522]
Comments from this PR https://github.com/microsoft/semantic-kernel/pull/3517

I also question whether this should instead be an IList<ChatMessage> instead of a List<ChatMessage>, so that we can add extra validation and behavior specific to ChatHistory, e.g. ensuring that Add(null) throws.

You added = string.Empty to the property initializer. If someone passes in a null role / content, what do you want to do? Should they still end up as empty? Throw?

**Comment by stephentoub** [comment]
Today, every time a ChatHistory is submitted to the {Azure} OpenAI service, the entire history is duplicated into the corresponding object model for the Azure SDK.  What would it look like instead if the SK ChatMessage objects wrapped the corresponding Azure SDK ChatMessage types, such that the object model didn't need to be recreated each time?  Presumably that would mean ChatHistory couldn't just be a `List<ChatMessage>`, because that forces a particular storage mechanism, and requires that the base `List<T>` APIs all work. It would likely need to change to be an `IList<T>`.  And what about creating the new ChatMessage instances... if a ChatHistory is created via a call to IChatCompletion.CreateNewChat, should a chat message be created via a ChatHistory.CreateNewMessage or some such new virtual method?  Otherwise, how would it wrap the appropriate instance from the service?

It might be worth prototyping this out.

**Comment by kcadduk** [comment]
I'm hoping this is the correct place, I'll open a separate issue if not, if you're revisiting a the design, it would be helpful if the data models needed like ChatHistory and ChatMessage were in some abstraction layer or abstracted in some other way, potentially implementing some interface.

As a consumer of the package, I'm tightly coupling my application to your models, where-as it would be nice to simply implement some interface and not have that tight coupling.

**Comment by markwallace-microsoft** [comment]
We also need to ensure that our chat history and message abstractions will support GPT Vision https://platform.openai.com/docs/guides/vision i.e. the ability for a message to have multiple different types of chat content

**Comment by kcadduk** [comment]
To be able to run `IChatCompletion.GenerateMessageStreamAsync` i need to pass in the `ChatHistory` which is a list of `ChatMessage`.

I want to be able to persist `ChatMessage` to a database, In my domain, Chat Messages belong to users and have timestamps and audit tracking information. Because it is a concretion, my Entity now needs to be a `ChatMessage` and have it as a base class. Especially because I want to extend the columns recorded on a `ChatMessage` yet still be able to pass it into Semantic Kernel. 

This is a little bit heavy, and means that I must make other libraries of my solution reliant upon the whole SemanticKernel Library. Especially my Domain library which sits at the heart of my Clean Architecture solution has almost no dependencies.

Semantic Kernel is an Infrastructure Layer concern. Not a domain concern.

Or I have to implement a converter that can take my domain `DomainChatMessage` and convert it to a SK `ChatMessage` again, very confusing because I now have two concretions that are basically the same thing. What is the difference between `ChatMessage` and `DomainChatMessage` that overlap in field names but aren't technically compatible with each other.

Now, if there were an abstractions or models package (Like many other packages out there, where a smaller abstractions library allows you to implement data objects or simple contracts without the bloat of a full library) I could simply make my `DomainChatMessage` implement `IChatMessage` and pass it freely into Semantic Kernel. I can also use my Domain Library in other products that are nothing like a chat-bot nor want to have a dependency on the entirety of Semantic Kernel.

**Comment by dmytrostruk** [comment]
@kcadduk 
> This is a little bit heavy, and means that I must make other libraries of my solution reliant upon the whole SemanticKernel Library. Especially my Domain library which sits at the heart of my Clean Architecture solution has almost no dependencies.

That's correct, you should try to avoid referencing other dependencies in your Domain library.

> Or I have to implement a converter that can take my domain `DomainChatMessage` and convert it to a SK `ChatMessage` again, very confusing because I now have two concretions that are basically the same thing. What is the difference between `ChatMessage` and `DomainChatMessage` that overlap in field names but aren't technically compatible with each other.

I'm not sure I understand why it's confusing. As you said, you want to be able to extend `ChatMessage` with your additional properties, like timestamps or audit tracking information. But it should not be an extension, it should be your own separate domain entity. 

You can create your `DomainChatMessage` with all necessary properties based on your business scenario, and use it in all places of your business logic. When you want some interaction with AI, you include Semantic Kernel in your Infrastructure Layer, map `DomainChatMessage` to `ChatMessage` and make a request.  

The difference between `ChatMessage` and `DomainChatMessage` is that `ChatMessage` comes from `Microsoft.SemanticKernel` SDK. As soon as Semantic Kernel will update or rename some properties in `ChatMessage`, your domain and business logic will be impacted as well, and it should not be the case. So, in order to have more flexibility and less problems in the future, I would suggest using your own models on Domain level, and map it to SK models on Infrastructure level.

> Now, if there were an abstractions or models package (Like many other packages out there, where a smaller abstractions library allows you to implement data objects or simple contracts without the bloat of a full library) I could simply make my `DomainChatMessage` implement `IChatMessage` and pass it freely into Semantic Kernel. I can also use my Domain Library in other products that are nothing like a chat-bot nor want to have a dependency on the entirety of Semantic Kernel.

The point is, that we do have separate package with abstractions. Models `ChatHistory` and `ChatMessage` live in that package: https://www.nuget.org/packages/Microsoft.SemanticKernel.Abstractions/1.0.0-rc3. 

You should be able to reference just this project and work with `ChatMessage` model. But, as you mentioned, your Domain layer has almost no dependencies, but `Microsot.SemanticKernel.Abstractions` is still a dependency. If you want more control and flexibility, the Domain layer should remain decoupled from any specific framework, including classes from other SDKs.

Let me know if that makes sense, thank you!

**Comment by kcadduk** [comment]
Thanks for the feedback. Sure, all that makes sense. I'll revisit the Chat Message design. Consider just mapping from one to the other in infrastructure. I'm just trying to find a happy place.

Thanks
