### ISSUE TITLE
Python: Error Raised for Maximum Content Length When Reusing the Same Kernel Multiple Times

### ISSUE THREAD

**Issue by samidarko** [microsoft/semantic-kernel#3559]
**Describe the bug**

Hi, I'm not entirely sure this is a bug. Maybe I'm just handling the kernel the wrong way but what is the right way then?

I created a ChatService such as:

```python
class ChatService:
    def __init__(self, azure_endpoint: str, azure_api_key: str) -> None:
        self._kernel = sk.Kernel()
        self._kernel.add_chat_service(
            "azure_gpt4",
            AzureChatCompletion(
                "gpt-4",
                azure_endpoint,
                azure_api_key,
            ),
        )
        self._kernel.set_default_chat_service("azure_gpt4")
        self._chat = self._kernel.register_semantic_function(
            skill_name="Chatbot",
            function_name="chat",
            function_config=create_semantic_function_chat_config(
                "{{$input}}",
                chat_config_dict,
                self._kernel,
            ),
        )

    async def chat(self, prompt: str):
        result = await self._kernel.run_async(self._chat, input_str=prompt)
        return result

async def run_chat():

    # fail if service is persisted
    chat_service = ChatService(azure_endpoint="...", azure_api_key="api key")

    while True:
        prompt = input()
        # doesn't fail if I create a new service at each iteration
        # chat_service = ChatService(azure_endpoint="...", azure_api_key="api key")
        output = await chat_service.chat(prompt)
        print(output)

 asyncio.run(run_chat())
```

This code will raise the following error when triggering the chat multiple times:

the `result.last_error_deescription` contains:

```
(<ErrorCodes.ServiceError: 6>, \'AzureChatCompletion failed to complete the chat\', InvalidRequestError(message="This model\'s maximum context length is 8192 tokens. However, you requested 8377 tokens (7877 in the messages, 500 in the completion). Please reduce the length of the messages or completion.", param=\'messages\', code=\'context_length_exceeded\', http_status=400, request_id=None))
```

**To Reproduce**
If you run this code with the chat service instantiated outside of the loop it will fail.
If you create a new service at every iteration it doesn't fail.
The model is GPT4 on Azure.

You can use this [demo app](https://github.com/samidarko/semantic_kernel_issue) to reproduce, see screenshot:

![img](https://github.com/microsoft/semantic-kernel/assets/2159096/f638119a-6c36-4de9-8588-1896b8c07ca0)

**Expected behavior**
I wasn't expecting this code to fail assuming I could persist the kernel.

**Platform**
 - OS: Linux Gentoo and MacOS
 - IDE: [e.g. Visual Studio, VS Code]
 - Language: Python
 - Source: semantic-kernel==0.3.15.dev0

**Additional context**

We tried different approaches. It doesn't seem to be about the semantic function itself because getting the function in the chat method at every call (like `chat = self._kernel.skills.get_function("Chatbot", "chat")`) doesn't fix the problem. Only creating a new kernel does. 

So it seems the kernel add something to the prompt but adding a logger in DEBUG mode (like `self._kernel = sk.Kernel(log=logger)`) doesn't show anything else that the prompt that worked the first time.

**Comment by eavanvalkenburg** [comment]
@samidarko can you share a bit more of your code, I see a function called `create_semantic_function_chat_config` what does that do, it does seem like you are just adding multiple messages into the _messages object inside of a ChatPromptTemplate and as you go those get sent to the API as a complete set, you should be able to look at the full message history by looking at `self._chat.function_config.prompt_template.messages`, there is currently no native way to truncate that as you go in order to reduce this issue, but I will make a note of that!

**Comment by samidarko** [comment]
@eavanvalkenburg did you see the more complete example I added? https://github.com/samidarko/semantic_kernel_issue

**Comment by eavanvalkenburg** [comment]
Thanks @samidarko, clear now, the issue is indeed simply that the chat_prompt.messages object keeps getting larger and since that is passed to the service as a whole, you indeed at some point run out of token room. The easiest way right now to get around this is to manually truncate the messages in the chat_prompt_template.messages (the reason it does work when recreating is because the function `create_semantic_function_chat_config` also runs which creates a new chat_prompt_template with a new messages list). For v1 we are redoing a lot of things around this and then it also becomes easier to do this kind of truncation.
