### ISSUE TITLE
.Net: The class KernelPromptTemplateFactory is missing

### ISSUE THREAD

**Issue by DrEight** [microsoft/semantic-kernel#3607]
If I reference the SK nuget package, the class KernelPromptTemplateFactory is missing.
I see the class in the [source code](https://github.com/microsoft/semantic-kernel/blob/main/dotnet/src/SemanticKernel.Core/TemplateEngine/KernelPromptTemplateFactory.cs).
Also the class KernelPromptTemplateEngine is missing, even if in beta #8 it should still be around.
Am I missing something ?

**Comment by HSven1611** [comment]
I found `Microsoft.SemanticKernel.TemplateEngine.Basic.BasicPromptTemplateFactory` and it seems to work. @DrEight  maybe this helps ...

**Comment by matthewbolanos** [comment]
If you're using Beta8, you should be able to get it working by following this sample: https://github.com/microsoft/semantic-kernel/blob/dotnet-1.0.0-beta8/dotnet/samples/KernelSyntaxExamples/Example64_MultiplePromptTemplates.cs

The repo currently handles prompt template engines slightly different than Beta8, which is why you are likely having issues finding the right classes. In v8, you should be using one of the following:
- `AggregatorPromptTemplateFactory`
- `BasicPromptTemplateFactory`
- `HandlebarsPromptTemplateFactory`

The are in the following package for Beta8:
- `using Microsoft.SemanticKernel.TemplateEngine;`
- `using Microsoft.SemanticKernel.TemplateEngine.Basic;`
- `using Microsoft.SemanticKernel.TemplateEngine.Handlebars;`
