### ISSUE TITLE
.Net: Example52_ApimAuth -- Failed - Needs more comments

### ISSUE THREAD

**Issue by teresaqhoang** [microsoft/semantic-kernel#3844]
**Describe the bug**
> A clear and concise description of what the bug is.

1. Needs comments on what the point of this Example is showcasing, i.e., summary comment before the class definition
1. Link is broken, should be `https://learn.microsoft.com/en-us/semantic-kernel/deploy/use-ai-apis-with-api-management`
![image](https://github.com/microsoft/semantic-kernel/assets/125500434/13d567cf-ffdd-47cc-bb68-48bf2699ca39)

**Platform**
 - OS: Windows
 - IDE: VS Code Terminal
 - Language: C#
 - Source: V1 Release Candidate Bug Bash

**Comment by glahaye** [comment]
@matthewbolanos I can't for the life of me get this running. Is there an easier way to test accessing AOAI through APIM?

Alternatively, do you have an already configured setup that I can just point the code to in order to test it?

**Comment by matthewbolanos** [comment]
Looks like the one we had got deleted. @glahaye, are you still blocked?

**Comment by glahaye** [comment]
@matthewbolanos I'm setting up another from scratch.

**Comment by glahaye** [comment]
@matthewbolanos @alliscode I spent the best part of the day wrestling with this issue.

I was able to get an instance of APIM to a state where I could invoke OpenAI through the Azure Portal's APIM test page **after modifying the inference.json file provided** in the https://learn.microsoft.com/en-us/semantic-kernel/deploy/use-ai-apis-with-api-management blog post. I _believe_ the provided inference.json file is incorrect / broken (with regards to appending the "openai" path to the base URL).

However, despite surmounting that problem, I was never able to use Oauth to access OpenAI through APIM. I'm not an OAuth or APIM expert but do have some experience dealing with those. The current blog entry is not foolproof enough for a fool of my level to get SK to work on APIM with Oauth.

I am tempted to believe the code and instructions are not valid and would recommend just deleting this example.

Alternatively, I can spend a couple more days getting to learn more about APIM and Oauth to make this work instead of tackling other issues.

Which path do you prefer I take?
