### ISSUE TITLE
.Net -  After update RC.1 , can not run in WithAzureOpenAIChatCompletion

### ISSUE THREAD

**Issue by kinfey** [microsoft/semantic-kernel#3962]
**Describe the bug**

I upgrade RC1 , run 

`
Kernel kernel = new KernelBuilder()
            .WithAzureOpenAIChatCompletion("dp","modelid","endpoint","key")
            .Build();

'

**To Reproduce**
1. run it in polyglot 
2. See error

Error: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.

File name: 'Microsoft.Bcl.AsyncInterfaces, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
at Submission#5.<<Initialize>>d__0.MoveNext()
at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
at Submission#5.<Initialize>()
at Submission#5.<Factory>(Object[] submissionArray)
at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.RunSubmissionsAsync[TResult](ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, StrongBox`1 exceptionHolderOpt, Func`2 catchExceptionOpt, CancellationToken cancellationToken)

**Comment by stephentoub** [comment]
> Steps to reproduce the behavior:
> run it in polyglot

Can you provide a more detailed repro? What's the complete code you're using? (The repro doesn't include referencing the relevant packages, for example) 

@colombod, can you help with this?

My guess is that however polyglot notebooks is loading things, it's ending up loading something that has a dependency on an older version of Microsoft.Bcl.AsyncInterfaces, then trying to load this code into the same AssemblyLoadContext/AppDomain, failing to then load the new version of the same M.B.AsyncInterfaces assembly into the same context/domain, and then it's failing because of the dependency on the new version.

**Comment by dmytrostruk** [comment]
@stephentoub I received the same problem while updating dotnet notebooks, I think it's because C# Polyglot Notebooks don't support .NET 8 yet:
![image](https://github.com/microsoft/semantic-kernel/assets/13853051/9e6816e5-3d45-4f29-bfd1-283486e87aca)

I found related work regarding .NET 8 support, these PRs were already merged 2 weeks ago but it looks like they are not released yet:
https://github.com/dotnet/interactive/pull/3336
https://github.com/dotnet/vscode-dotnet-pack/pull/515

**Comment by colombod** [comment]
we are releasing .NET8 support this week. it is currently available if you switch the extension in pre-release

**Comment by dmytrostruk** [comment]
@colombod I tried to switch extension to pre-release:
![image](https://github.com/microsoft/semantic-kernel/assets/13853051/4acc3e8a-d2c8-4e0f-91d3-6b7f002b705a)

But I still receive the same issue:
![image](https://github.com/microsoft/semantic-kernel/assets/13853051/8bbcaef7-5ca8-4d30-acea-77fa771c3a9c)

Is there anything I'm missing for workaround?

**Comment by WeihanLi** [comment]
There's a new release from dotnet-interactive now

https://github.com/dotnet/interactive/releases/tag/v1.0.4605020
