### ISSUE TITLE
.Net: Configurable handlebars planner prompt

### ISSUE THREAD

**Issue by rnortje-sygnia** [microsoft/semantic-kernel#4067]
The handlebars planner is definitely more powerful and useful.  However, we find that being able to add extra domain knowledge/content that explains terms or concepts allows it to better choose the appropriate functions. The current prompt is inaccessible, and one cannot inject extra content into it, thus limiting its usability in certain domains. I understand that the prompt is very specialized, and one would not necessarily like users to break it, so if you want to keep the prompt closed to modification, I suggest some way to inject additional content, maybe via the configuration settings. Or alternatively allow us to specify our own prompt to use as an alternative to the built in one. Not sure how you see it best to tackle this, but it will be much appreciated if this can be added.  Currently I am forced to build my own planner from source code, which is not sustainable in the longer term.

**Comment by matthewbolanos** [comment]
@teresaqhoang, is this something that will be supported when you enable partials support in the Handlebars template engine?

**Comment by teresaqhoang** [comment]
Yes, that's exactly what the partials will help do! 

@rnortje-sygnia The plan is to split each section of the planner into isolated partials that we'll structure together piece-by-piece, so users will have more control on the order / structure of the planner prompt (omit or add any custom sections of their choosing).

Still thinking the design of exactly how to do this, where certain sections may be gated from omission, but what kind of additional content are you thinking of adding and where do you see that fitting into the existing prompt?

**Comment by rnortje-sygnia** [comment]
We have some unique domain knowledge that helps the LLM understand the domain, specifically around how we use terms and interpret relationships. Currently, you could possible send that in as part of the ask I suppose. But in order for it to understand the descriptions of the functions we provide, it needs to understand our domain language, we found by adding this to most of our prompts we improve the ability of the LLM to reason over our domain quite drastically.

Now the handlebars planner is quite unique, in that it requires very specific instruction on how to get efficient plans generated using handlebars and all the helpers etc. The helpers you add dynamically, the core prompt on efficient handlebars usage etc I would not want to change as you guys would be the experts in how to get it working best, but we would need to be able to add custom instructions and content around the domain usage. For now we have tried to add this to our function descriptions, but it leads to repetitive very length descriptions. Personally, since you can add context variable to the prompt easily, I would just provide some extra config options for the planner where you can set extra content and variable for it to use when generating the plan, if not supplied these area then just skipped by the planner, similarly to the if statements you have around the allow loops functions.

But as you say, your solution below will address this if the planner prompt sections can be controlled.

We would typically add something like this to the prompt:

“When evaluating which functions to use, consider the extra domain knowledge provided, this will provide guidance in better understanding the context functions can be used in

{{DOMAIN_CONTEXT}}
“”

Or something similar, this is basically what we do with most of our prompts and it makes a massive difference in the quality of results.

**Comment by Cotspheer** [comment]
@teresaqhoang maybe to add my use cases:

- I need a way to instruct the LLM that the last step should be a call to a certain plugin. Currently I try to abuse the intent / goal of the planner to provide that information. But with a custom prompt template I could adjust the prompt to instruct the LLM to do so.
- I need custom arguments for example to provide the users current language. I have language dependent stores / indexes and the retrieval works best when it matches the user's current language. Also it would allow to provide that language to other plugins in order to avoid translations but to generate the answer directly in the requested language.
- I need to add additional information to the prompt as the LLM invokes the plugins the wrong way. Currently I have to abuse the description. But with a custom prompt template / or delegate I could add that to the yaml myself. See: 
  - #4439
  - #3258 

**My higher level use case:**

I want that an Agent creates an action plan to get all the information that might be needed to fit the users intent so that the conversation plugin can create the final answer with all the knowledge retrieved. The knowledge is retrieve through various specialized plugins that do not create the final answer. The final prompt has specific sections for that knowledge so the LLM has the domain context (meaning of the provided knowledge) and can use it accordingly. Also it sets the scene and how the Agent should act.

I see myself in the same position as @rnortje-sygnia to create a custom implementation to achieve this level of detail which is time consuming and not sustainable. The support to adjust the template or to inject custom instructions would be great. Maybe even both is needed.

Thank you in advance!

**Comment by teresaqhoang** [comment]
Hey @Cotspheer , @rnortje-sygnia 

We added more flexibility to the Handlebars prompts with the following PRs:
- https://github.com/microsoft/semantic-kernel/pull/4918
- https://github.com/microsoft/semantic-kernel/pull/5005

Now, you have options to:
- Override the CreatePlan prompt completely with your own custom prompts
- Inject additional context into the default prompt
- Define initial kernel arguments to pass into the planner on creation and execution (the same set of variables must be defined on both actions)

You can check out the latest samples in [Example65](https://github.com/microsoft/semantic-kernel/blob/5b8deb67453c111ad41d38e06c65d64be140db8e/dotnet/samples/KernelSyntaxExamples/Example65_HandlebarsPlanner.cs#L319C17-L319C50) for reference on how to use these new options.
