### ISSUE TITLE
.Net: Could not load type 'Microsoft.SemanticKernel.Orchestration.SKContext' from assembly 

### ISSUE THREAD

**Issue by Alerinos** [microsoft/semantic-kernel#4138]
Error:
```
System.Reflection.ReflectionTypeLoadException: „Unable to load one or more of the requested types.
Could not load type 'Microsoft.SemanticKernel.Orchestration.SKContext' from assembly 'Microsoft.SemanticKernel.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=f300afd708cefcd3'.
Could not load type 'Microsoft.SemanticKernel.Orchestration.SKContext' from assembly 'Microsoft.SemanticKernel.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=f300afd708cefcd3'.”
```

Same error as with SqlClient:
https://github.com/dotnet/SqlClient/issues/1930

**Comment by dmytrostruk** [comment]
Hi @Alerinos ! `SKContext` class has been removed starting from RC version of Semantic Kernel. In short, if you want to set variables for your prompts, you can use `KernelArguments` class.

This document contains list of recent changes in SK:
https://devblogs.microsoft.com/semantic-kernel/release-candidate-1-for-the-semantic-kernel-net-sdk-is-now-live/

By following link, you can find dotnet notebooks with usage examples:
https://github.com/microsoft/semantic-kernel/tree/main/dotnet/notebooks

If you have a specific scenario and need an assistance, please let us know. Thank you!

**Comment by dmytrostruk** [comment]
@Alerinos Could you please share more details about error including:
1. Code sample
2. Version of Semantic Kernel.
3. Version of .NET.

Thank you!

**Comment by strikene** [comment]
> 嗨 ！ 类已从 RC 版本的 Semantic Kernel 开始删除。简而言之，如果你想为你的提示设置变量，你可以使用类。`SKContext``KernelArguments`
> 
> 本文档包含 SK： https://devblogs.microsoft.com/semantic-kernel/release-candidate-1-for-the-semantic-kernel-net-sdk-is-now-live/ 的最新更改列表
> 
> 通过以下链接，可以找到包含使用示例的 dotnet 笔记本：通过以下链接，可以找到包含使用示例的 dotnet 笔记本：https://github.com/microsoft/semantic-kernel/tree/main/dotnet/notebooks
> 
> 如果您有特定情况并需要帮助，请告诉我们。谢谢！

I wonder if Microsoft.SemanticKernel.TemplateEngine.IPromptTemplate in Beta8 has a replacement in RC3 or has been deprecated. 
We are trying to upgrade from Beta8 to RC3 However, we are getting all sorts of compiler errors like never before, FunctionResult, SKContext, IPromptTemplate, SequentialPlanner, ISKFunction, KernelResult...

**Comment by strikene** [comment]
> Hi @Alerinos ! `SKContext` class has been removed starting from RC version of Semantic Kernel. In short, if you want to set variables for your prompts, you can use `KernelArguments` class.
> 
> This document contains list of recent changes in SK: https://devblogs.microsoft.com/semantic-kernel/release-candidate-1-for-the-semantic-kernel-net-sdk-is-now-live/
> 
> By following link, you can find dotnet notebooks with usage examples: https://github.com/microsoft/semantic-kernel/tree/main/dotnet/notebooks
> 
> If you have a specific scenario and need an assistance, please let us know. Thank you!

I wonder if Microsoft.SemanticKernel.TemplateEngine.IPromptTemplate in Beta8 has a replacement in RC3 or has been deprecated.
We are trying to upgrade from Beta8 to RC3 However, we are getting all sorts of compiler errors like never before, FunctionResult, SKContext, IPromptTemplate, SequentialPlanner, ISKFunction, KernelResult...

**Comment by dmytrostruk** [comment]
> I wonder if Microsoft.SemanticKernel.TemplateEngine.IPromptTemplate in Beta8 has a replacement in RC3 or has been deprecated.

@strikene You can find it under root namespace - `Microsoft.SemanticKernel`:
https://github.com/microsoft/semantic-kernel/blob/b01dac675fbc57dfc6cc3b0555ab1eae99c581cc/dotnet/src/SemanticKernel.Abstractions/PromptTemplate/IPromptTemplate.cs#L6-L11


> We are trying to upgrade from Beta8 to RC3 However, we are getting all sorts of compiler errors like never before, FunctionResult, SKContext, IPromptTemplate, SequentialPlanner, ISKFunction, KernelResult...

Yes, the migration from beta to RC is harder than usual due to big number of new changes and improvements. As we are preparing to v1 release, we want to make sure that each functionality in SK provides best value for our users.

**Comment by strikene** [comment]
> > I wonder if Microsoft.SemanticKernel.TemplateEngine.IPromptTemplate in Beta8 has a replacement in RC3 or has been deprecated.
> 
> @strikene You can find it under root namespace - :`Microsoft.SemanticKernel`
> 
> https://github.com/microsoft/semantic-kernel/blob/b01dac675fbc57dfc6cc3b0555ab1eae99c581cc/dotnet/src/SemanticKernel.Abstractions/PromptTemplate/IPromptTemplate.cs#L6-L11
> 
> > We are trying to upgrade from Beta8 to RC3 However, we are getting all sorts of compiler errors like never before, FunctionResult, SKContext, IPromptTemplate, SequentialPlanner, ISKFunction, KernelResult...
> 
> Yes, the migration from beta to RC is harder than usual due to big number of new changes and improvements. As we are preparing to v1 release, we want to make sure that each functionality in SK provides best value for our users.

Thank you for your help, it saved me a lot of time. I also have a tricky question



We've created a function on Beta8 that breaks down complex actions into single steps, and we'll output individual steps. Then create a plan with a separate step using 'SequentialPlanner', which works great. It avoids the 'model hallucination' when multiple functions are selected


For a single plan created, it is actually the result of the previous plan that he uses when he executes it. It's easy to use SKContext to pass the variables of the previous step in a single step. Experimentally, this method is great for creating complex tasks with 'memory', but after upgrading the RC3 it seems that 'handlebar' does not provide such a way to allow us to pass on the results of the previous plan, as this result can be very large or even more than 32k. 
 Because 'handlebars' create variables in the plan, there is no way to change its value externally. I don't know what I should do at this point. On the one hand, 'handlebars' are indeed suitable for creating complex tasks, but if the task itself does not mention any function-related information, it is difficult to choose the function correctly, for example: I need to buy paint, my house length, width and height, the unit price of paint, I need to calculate the price of paint. At this point, we break down the task and give some guidance, so that the AI can choose the correct Math function.

**Comment by dmytrostruk** [comment]
@strikene Could you please share some code examples which will demonstrate the use case and what is missing in current implementation? That would be very helpful, thanks a lot!

**Comment by dmytrostruk** [comment]
Closing this issue, as response to initial question was provided. Feel free to create another issue if some of the listed problems are unresolved.
