### ISSUE TITLE
.Net: MongoDB memory store connector should use internal ObjectId as Id and a separate string metadata.key

### ISSUE THREAD

**Issue by dviry** [microsoft/semantic-kernel#4315]
The current MongoDB memory store connector uses the MemoryEntryMetadata "key" as the MongoDB "id" - and duplicates it - once in the [MemoryRecordMetadata](https://github.com/microsoft/semantic-kernel/blob/70eddb5a01c66c6149a4103cf397357f2ecdcc23/dotnet/src/Connectors/Connectors.Memory.MongoDB/MongoDBMemoryRecordMetadata.cs#L31) which btw shows up as _id (because it's attributed with BsonId) and once in the [MemoryEntry](https://github.com/microsoft/semantic-kernel/blob/70eddb5a01c66c6149a4103cf397357f2ecdcc23/dotnet/src/Connectors/Connectors.Memory.MongoDB/MongoDBMemoryEntry.cs#L19) itself.

That is not only architecturally wrong (using a string id in a MongoDB has a lookup/storage performance hit, it should be ObjectId), but it also means you cannot have multiple MemoryEntries for the same referenced Key (which is the issue I am having) due to the Upsert method using the Key to identify the MongoDB entry.

I'd suggest separating the internal MongoDB unique MemoryEntry.ID (should be of type ObjectId) -  from the MemoryEntryMetadata.Key (should remain as string type) - as it used to be in the [original connector](https://github.com/kbeaugrand/SemanticKernel.Connectors.Memory.MongoDB/blob/59c16cd0446dbf01a8e635a07bd952b17120d42c/src/Connectors.Memory.MongoDB/MongoDBMemoryEntry.cs#L29).

**Comment by williambohrmann3** [comment]
Would it be helpful to add a `[BsonRepresentation(BsonType.ObjectId)]` attribute to the [Id](https://github.com/microsoft/semantic-kernel/blob/13a4b4e92cfb664df116f494aac97e7e3badfb49/dotnet/src/Connectors/Connectors.Memory.MongoDB/MongoDBMemoryEntry.cs#L19) property? Only asking this because when I attempt a [semantic search](https://learn.microsoft.com/en-us/dotnet/api/microsoft.semantickernel.memory.isemantictextmemory.searchasync?view=semantic-kernel-dotnet#microsoft-semantickernel-memory-isemantictextmemory-searchasync(system-string-system-string-system-int32-system-double-system-boolean-microsoft-semantickernel-kernel-system-threading-cancellationtoken)) against MongoDB, I am getting `An error occurred while deserializing the Id property of class Microsoft.SemanticKernel.Connectors.MongoDB.MongoDBMemoryEntry: Cannot deserialize a 'String' from BsonType 'ObjectId'.
`

**Comment by markwallace-microsoft** [comment]
Closing as we have new memory abstractions and will be obsoleting the old ones in the future.
