### ISSUE TITLE
.Net: Semantic Kernel Exception when running TextMemory Plugin Sample

### ISSUE THREAD

**Issue by AshD** [microsoft/semantic-kernel#4418]
**Describe the bug**
Running TextMemory Plugin Sample
https://github.com/microsoft/semantic-kernel/blob/main/dotnet/samples/KernelSyntaxExamples/Example15_TextMemoryPlugin.cs

in PART 4: TextMemoryPlugin Recall in a Prompt Function throws 
`Microsoft.SemanticKernel.KernelException: 'A function named argument must contain a name and value separated by a '=' character.'`

In line  
 `var aboutMeOracle = kernel.CreateFunctionFromPrompt(RecallFunctionDefinition, new OpenAIPromptExecutionSettings() { MaxTokens = 100 });`

Has the syntax for defining the Recall function changed? The below is the one from the sample.
```
            const string RecallFunctionDefinition = @"
Consider only the facts below when answering questions:

BEGIN FACTS
About me: {{recall='where did I grow up?'}}
About me: {{recall='where do I live now?'}}
END FACTS

Question: {{$input}}

Answer:
";
```

I am on dotnet 1.01 release and Kernel memory 1.0.1-alpha

Thanks,
Ash

**Comment by glahaye** [comment]
Looking at this...

**Comment by glahaye** [comment]
It turns out the CodeTokenizer routinely causes first-chance (caught) exceptions to determine whether tokens belong to function names of named argument blocks. This is inefficient but also can be startling depending on how one has set one's configuration for breaking on exceptions.

See PR #4471 for fix
