### ISSUE TITLE
.Net 6.0 : SemanticKernel compatibility with Azure Function v4 in .NET 6

### ISSUE THREAD

**Issue by alekssaf** [microsoft/semantic-kernel#4472]
I wanted to bring to your attention a compatibility issue we've encountered while using Semantic Kernel with Azure Functions v4 (.NET 6).
Upon integration, we noticed a dependency on 'Microsoft.Extensions.Logging.Abstractions' (Version 8.0.0.0) causing an error in the Azure Functions runtime. The specific error reads: "Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified."
This seems to indicate an incompatibility between Semantic Kernel and the Azure Functions v4, which may be attributed to the version disparity in the mentioned dependency.
We're reaching out to inquire if you or your team have encountered a similar issue and if any solutions or workarounds have been identified. Your insights would be highly valuable in navigating through this challenge.

**Additional context**
<TargetFramework>net6.0</TargetFramework>
<AzureFunctionsVersion>v4</AzureFunctionsVersion>
<PackageReference Include="Microsoft.SemanticKernel" Version="1.0.0-rc3" />

**Comment by stephentoub** [comment]
Can you use the Azure Functions isolated worker model?  This should all work fine there.

The Azure Functions in-process model runs into problems because the Functions host itself relies on the 6.0.x version of these nuget packages, and so anything loaded into that process that relies on a newer version of the nuget package will run into problems.

https://azure.microsoft.com/en-us/updates/ga-azure-functions-supports-net-8-in-the-isolated-worker-model/

**Comment by alekssaf** [comment]
Thank you, it is working fine.
