### ISSUE TITLE
Python: Add Notebooks as integration tests

### ISSUE THREAD

**Issue by matthewbolanos** [microsoft/semantic-kernel#4637]

**Comment by john0isaac** [comment]
I would like to work on fixing this.

**Comment by beman9** [comment]
I can take a stab at this. I had some time so worked on a script that tests the "getting_started" notebooks. It is able to test them all except for [06-memory-and-embedding.ipynb](https://github.com/microsoft/semantic-kernel/blob/main/python/samples/getting_started/06-memory-and-embeddings.ipynb?short_path=b2a7e2a#L281) due to the use of input() in a notebook. I haven't figured out a way around it yet.
