### ISSUE TITLE
.Net: GetPromptTemplate option does not work for HandlebarsPlanner

### ISSUE THREAD

**Issue by banduki** [microsoft/semantic-kernel#4660]
**Describe the bug**
The GetPromptTemplate planner option is ignored in the plan prompt creation for HandlebarsPlanner.

**To Reproduce**
1. Create a HandlebarsPlannerOptions, assign to GetPromptTemplate a string func delegate which returns any text
2. Create HandlebarsPlanner with those options
3. Create plan
4. View plan prompt (`plan.Prompt`)
5. See that GetPromptTemplate delegate is ignored and plan prompt contains only the text from the _CreatePlanPrompt.handlebars_ embedded resource

**Expected behavior**
The plan prompt should contain the string returned by the string delegate assigned to the GetPromptTemplate option.

**Platform**
 - OS: Windows 10
 - IDE: Visual Studio 2022
 - Language: C#
 - Source: SemanticKernel NuGets 1.1.0, latest code in SK repo main branch

**Additional context**
Fix should change first line in HandlebarsPlanner.GetHandlebarsTemplateAsync() to:
`var createPlanPrompt = this._options.GetPromptTemplate?.Invoke() ?? this.ReadPrompt("CreatePlanPrompt.handlebars");`

**Comment by banduki** [comment]
@matthewbolanos This is my first time participating in an open source repository. Can I code the fix and create a PR?

**Comment by gitri-ms** [comment]
> @matthewbolanos This is my first time participating in an open source repository. Can I code the fix and create a PR?

@banduki That would be great! Please do and I'll review :smile:

**Comment by teresaqhoang** [comment]
Hi @banduki , apologies, we had a couple of stale, unimplemented options in the HandlebarsPlanner. These have since been removed, and new options have been added for prompt configuration, namely two called `GetAdditionalPromptContext` and `CreatePlanPromptHandler`. The latter can be used to override the prompt completely, whereas the former allows you to inject domain context into our engineered prompt. 

See the two latest samples in [`Example65_HandlebarsPlanner` starting on line 361](https://github.com/teresaqhoang/semantic-kernel/blob/885873343e7e4432c99ecbeb898c4a957349750d/dotnet/samples/KernelSyntaxExamples/Example65_HandlebarsPlanner.cs#L361)

Closing this issue as resolved
