### ISSUE TITLE
TooManyRequests - Retry logic

### ISSUE THREAD

**Issue by KSemenenko** [microsoft/semantic-kernel#4744]
We need the logic of working with TooManyRequests, at the moment the operation is simply suspended. But it would probably be good to wait a bit.

This is especially important when the planners are working.
in ClientCore.cs
``` cs
private static async Task<T> RunRequestAsync<T>(Func<Task<T>> request)
{
    try
    {
        return await request.Invoke().ConfigureAwait(false);
    }
    catch (RequestFailedException e)
    {
        throw e.ToHttpOperationException();
    }
}
```
so we can add here some retry logic. what do you think?

also this is helps for embedding in Kernel Memroy, becase when I upload 300 pages coument it never works =) because of TPM limit for azure ada2

**Comment by stephentoub** [comment]
That's all already configurable via the DI system, eg
https://github.com/microsoft/semantic-kernel/blob/main/dotnet/samples/KernelSyntaxExamples/Example08_RetryHandler.cs

**Comment by KSemenenko** [comment]
@stephentoub  this is amazing news
```
builder.Services.ConfigureHttpClientDefaults(c =>
        {
            // Use a standard resiliency policy, augmented to retry on 401 Unauthorized for this example
            c.AddStandardResilienceHandler().Configure(o =>
            {
                o.Retry.ShouldHandle = args => ValueTask.FromResult(args.Outcome.Result?.StatusCode is HttpStatusCode.Unauthorized);
            });
        });```
        this righ?

**Comment by KSemenenko** [comment]
@stephentoub  is it work for Azure OpenAI? for azure there is Azure OpenAI client

**Comment by stephentoub** [comment]
> is it work for Azure OpenAI?

Yes. SK will configure OpenAIClient with whatever HttpClient it can get from its service provider, unless you explicitly override that.

Is it not working for you? Can you share a repro?

**Comment by KSemenenko** [comment]
Looks liks it works fine, I will do more test, but seems all is good!
thanks a lot! this is amazing functionality!

**Comment by KSemenenko** [comment]
@stephentoub it works perfeclty for SK, but not for Kernel Memory, and for me biggest issue is embeddig for KM.

**Comment by stephentoub** [comment]
@KSemenenko, are you referring to the embedding generators in SK, or are you referring to https://github.com/microsoft/kernel-memory?

@dmytrostruk or @dluc might be able to comment.

**Comment by KSemenenko** [comment]
All is fine, thank you! I found we can pass httpClient into KM, and also there is a parameter MaxRetry.

thanks a lot!

**Comment by CharlieDigital** [comment]
The link here goes to a 404: https://github.com/microsoft/semantic-kernel/blob/main/dotnet/samples/KernelSyntaxExamples/Example08_RetryHandler.cs

The examples now show using a filter-based approach like this: https://github.com/microsoft/semantic-kernel/blob/main/dotnet/samples/Concepts/Filtering/RetryWithFilters.cs

However, what's not obvious here looking at the example is how to consume header values like `Retry-After` to wait more accurately.

`HttpOperationException` (https://github.com/microsoft/semantic-kernel/blob/main/dotnet/src/SemanticKernel.Abstractions/Http/HttpOperationException.cs#L15) does not currently provide a mechanism to access the headers.  Since this information is commonly included in the headers of the response, it would be useful to surface a readonly collection here with the headers so handlers can potentially extract a `Retry-After` (or equivalent) header to use for setting a reasonable retry delay.
