### ISSUE TITLE
.Net: Add text-to-speech and speech-to-text AI connector

### ISSUE THREAD

**Issue by dmytrostruk** [microsoft/semantic-kernel#4840]
Add text-to-speech and speech-to-text AI connector backed by Azure speech to text and Whisper

**Comment by damian-666** [comment]
Ive tried some whisper based voice to text and they are not usable and they are over the wire.

is there a way to access the low latency voice to text  under (Voice Access for windows  accessibly and make it a first class feature, combined with UI discovery and context awareness.   For commands, or mabye other Arduino based speech to text and or diction / brielle devices , because with latency and web its unusable, it needs a dedicated DSP for hot words and interrupts to work, and a second pass to apply context to correct guess.  This can be generalized to work on many platfroms.  wih the same code.   I've tried pico and rhino and its unusable on my system.  Ive tried whisper based one an unusable.  voice access can be refined as typos completion and via OCR, LLV vectorization, maybe PHi and refinement via focus.  For example i can open a file menu and tell chant chat gpt that voice access didnt guess correctly, then take a screen shot, it will fix the guess to fit the File menu choices.  When I do spell check I use two prompts, first fix only typos, without reinterpretation or grammar fixes,  then fix and list words that seem out of context.   Accessibility should be an optional first class UI that works with legacy apps, not an afterthought or a duplicated effort at least for discoverable UI via OCR, that happens in admin mode periodically, via that using the redundance accessibility apis and requiring developer maintenance through COM

**Comment by markwallace-microsoft** [comment]
PR's
https://github.com/microsoft/semantic-kernel/pull/4932
https://github.com/microsoft/semantic-kernel/pull/4933
