### ISSUE TITLE
.Net: Dotnet AddAzureOpenAITextEmbeddingGeneration not working with deploymentName, endpoint and ApiKey params

### ISSUE THREAD

**Issue by ericvdberge** [microsoft/semantic-kernel#4855]
**Describe the bug**
I am configuring my .net api to use Azure AI Search for the semantic kernel by adding the AddAzureOpenAITextEmbeddingGeneration extension for the IServiceCollection list by using this code:
```cs
services.
    AddAzureOpenAITextEmbeddingGeneration(
        options.DeploymentName,
        options.Endpoint,
         options.ApiKey
    );
```
With this configuration, I am just getting this wierd error, because i just want to connect my embedding and azure ai search index for my api: 
'Microsoft.SemanticKernel.OpenAIServiceCollectionExtensions.AddAzureOpenAITextEmbeddingGeneration(Microsoft.Extensions.DependencyInjection.IServiceCollection, string, string, string, string?, string?)' is for evaluation purposes only and is subject to change or removal in future updates. Suppress this diagnostic to proceed.'

**To Reproduce**
1. Go to Visual studio and create a .net 8 core api
2. Go to the program.cs and use the code as described in the bug description
3. Build the solution
4. See error with xode 'SKEXP0011', 'SKEXP0003', 'SKEXP0011', 'SKEXP0021', 'SKEXP0021' in The error list of visual studio

**Expected behavior**
I expect it to just connect with my azureOpenAITextEmbeddingService 'ada' to create an embedding from a user question and use that embedding to somehow search in my already created Azure Ai Search index

**Screenshots**
![AzureOpenAiTextEmbeddingError](https://github.com/microsoft/semantic-kernel/assets/32539664/a4399e8a-514f-467e-ab84-212c71e2210c)

**Platform**
 - OS: Windows
 - IDE: Visual Studio
 - Language: C#
 - Source: Microsoft.SemanticKernel namespace and nuget package

**Comment by dmytrostruk** [comment]
@ericvdberge Thanks for reporting this issue. Semantic Kernel SDK contains some experimental features, which may be changed/updated in the future, so these errors just notify you about that. In order to resolve this, you will need to suppress these errors by error code (e.g. SKEXP0011, SKEXP0003 and so on).

Here is more information about that:
https://github.com/microsoft/semantic-kernel/blob/main/dotnet/docs/EXPERIMENTS.md#experiments
![image](https://github.com/microsoft/semantic-kernel/assets/13853051/5ab43cca-83fd-4d9a-a137-0c3741dc1b5f)

**Comment by LiuKai115** [comment]
why i get error instead of warn for SKEXP0001?
