### ISSUE TITLE
.Net: In Plugins.Memory VolatileMemoryStore has a different namespace which is confusing/wrong (or it feels wrong)

### ISSUE THREAD

**Issue by joslat** [microsoft/semantic-kernel#4858]
**Describe the bug**
.Net: In the Microsoft.SemanticKernel.Plugins.Memory package, the VolatileMemoryStore class has Microsoft.SemanticKernel.Memory as its namespace which is confusing and differs from the rest of other elements in there.

**To Reproduce**
Look at the code 

**Expected behavior**
In my opinion all classes should share the same namespace or root namespace.

**Comment by dmytrostruk** [comment]
@joslat Thanks for reporting this issue.

`VolatileMemoryStore` class is the implementation of `Microsoft.SemanticKernel.Memory.IMemoryStore` interface. It's a lightweight alternative for existing memory connectors, like `Microsoft.SemanticKernel.Connectors.Chroma.ChromaMemoryStore` or `Microsoft.SemanticKernel.Connectors.Pinecone.PineconeMemoryStore`. 

`VolatileMemoryStore` is in-memory storage class, that is used for demonstration purposes only. It's not a Plugin, that's why it's not under `Microsoft.SemanticKernel.Plugins.Memory`. In ideal scenario, `VolatileMemoryStore` should live in separate package, just like other memory connectors, but we don't want to distribute it as separate package, because it is used for examples only. Maybe at some point we will move this class to other examples, but for now we placed it in `Plugins.Memory` package. 

> In my opinion all classes should share the same namespace or root namespace.

I agree, but it's not always the case, especially in SDK development. In SDK, we are defining the namespaces from usability and discoverability point of view, rather than package/folder location. 

Taking into account that `VolatileMemoryStore` is experimental and may be moved to examples in the future, I think it's fine to keep it as it is for now. Please let me know if that makes sense, thank you!

**Comment by joslat** [comment]
It does, thanks for the super detailed explanation @dmytrostruk - I owe you a beer! (at least)

**Comment by dmytrostruk** [comment]
@joslat I'm closing this issue as there are no actions to perform at this stage. Feel free to re-open it or create a new issue in case of further questions. Thank you!
