### ISSUE TITLE
.Net: ToolCallBehavior support with custom IChatCompletionService implementation

### ISSUE THREAD

**Issue by dsp05** [microsoft/semantic-kernel#4878]
Hi team, 
We are implementing `IChatCompletionService` using a custom proxy and it could not handle `ToolCallBehavior EnableFunctions` or `ToolCallBehavior RequireFunction` because the properties are either private or internal, any suggestion or workaround?
Thanks!

**Comment by markwallace-microsoft** [comment]
Hi @dsp05 
can you share some information about your use case?

We have provided `ToolCallBehavior` to support some OpenAI specific functionality and wanted to allow for extending this ourselves in the even OpenAI support new types of tools.

**Comment by markwallace-microsoft** [comment]
FYI @stephentoub

**Comment by stephentoub** [comment]
> We are implementing IChatCompletionService using a custom proxy

Can you elaborate more on this?

The intent was for these types to be specific to the OpenAI connector, and to have more general types/settings eventually at the base PromptExecutionSettings layer that could apply broadly to more connectors (right now only AutoInvokeKernelFunctions is supported at that level).

And as Mark started, details about the configuration have been kept private for now mainly to enable some wiggle room as the underlying Azure.AI.OpenAI SDK matures. Eventually it'd be fine I expect to make more public, but I'd be a tad hesitant to do so now. 

It'd be helpful to better understand the use case you have.

**Comment by dsp05** [comment]
Hi team, thanks for the reply!
We use a proxy class built on Azure.AI.OpenAI SDK to call AOAI, which has some extra functionalities e.g. load balancing and throttling. We use it to implement an `IChatCompletionService` and pass it to a `Kernel` or `KernelBuilder`. 

My question is when the caller sets the `OpenAIPromptExecutionSettings.ToolCallBehavior`, for `EnableKernelFunctions` and `AutoInvokeKernelFunctions`, the `IChatCompletionService` implementation can get the functions from the kernel and create the payload and send to the proxy class, but for `EnableFunctions` and `RequireFunction`, they can be created using public methods but external implementations of `IChatCompletionService` can't get the functions and create the payload because the properties and methods are not public.

**Comment by stephentoub** [comment]
> which has some extra functionalities e.g. load balancing and throttling

Is there a reason you implement this around AOAI rather than as an HttpClientHandler that you give to AOAI?

**Comment by dsp05** [comment]
Thanks for the suggestions! Unfortunately, it has to be like this, and we already have several layers around the AOAI client and corresponding factory classes. If I understand correctly, replacing it with an `AzureOpenAIChatCompletionService` will require a lot of refactoring and contract changes.

As a short-term plan, I think we can avoid using `EnableFunctions` and `RequireFunction`, or maybe reflection if really needed... What would be the future plan for `IChatCompletionService` and `ToolCallBehavior`? Will developers still be able to use their own `IChatCompletionService` implementation and have a way to get the functions from `ToolCallBehavior`?

**Comment by stephentoub** [comment]
> What would be the future plan for IChatCompletionService and ToolCallBehavior?

Right now, ToolCallBehavior is specific to the OpenAI connector: it's part of the namespace and assembly for AzureOpenAIChatCompletionService and OpenAIChatCompletionService. The intent was that these could surface everything that OpenAI supports, whereas IChatCompletionService is the lowest-level contract, doesn't necessarily support function calling, or if it does doesn't necessarily support it in the same way that OpenAI does (e.g. the idea of having a single function that the tool is required to invoke).

Every IChatCompletionService implementation conforms to that contract, but also has its own specializations, its own settings that are exposed on settings types related to that specific implementation. It's not expected that the settings types for custom implementation A make sense to custom implementation B.

I can imagine (no promises) in the future that the concrete types that Microsoft.SemanticKernel.Connectors.OpenAI.ToolCallBehavior produces could be made public and with the various settings configured on them.  I can also imagine that more general versions of these are exposed for any connector that supports some variation of function calling, though it's not clear to me at the moment what that would look like, since beyond "here are some functions you might be able to use" (which is already supported by setting a property on the base PromptExecutionSettings), there's likely to be significant variation in what different models/services support.

Your specific case seems to be trying to support everything AzureOpenAIChatCompletionService supports, duplicating all of its implementation, in order to layer in additional functionality.  That's fairly niche, and also something I'd discourage if you can achieve it in other ways.  It'd be better to not have to reimplement all of that logic (which is likely to evolve with additional support over time), and instead just wrap it or plug into its extensiblity, e.g. providing a custom HttpMessageHandler that supports throttling and/or load-balancing.  There's already existing .NET libraries that provide similar support and that can be plugged in via the DI system, e.g. https://www.nuget.org/packages/Microsoft.Extensions.Http.Resilience#readme-body-tab that provides retries, rate limiting (throttling), timeouts, circuit breaking, etc. Using that doesn't require replacing AzureOpenAIChatCompletionService; you just configure the services for the Kernel to use that, and it'll automatically be injected into the HttpClient handlers that AzureOpenAIChatCompletionService uses and passes to OpenAIClient.
