### ISSUE TITLE
.Net: Enhancements to Handlebars syntax

### ISSUE THREAD

**Issue by markwallace-microsoft** [microsoft/semantic-kernel#4892]
Following features are not working:

- `loops (each)` - not working at the moment, but tries to do so over a complex object generated by one of the functions: a JSON array-
- `array` - not working at the moment - to accumulate the results of the loop in an array

**Comment by joslat** [comment]
hi @markwallace-microsoft is there any way to have the handlebars process a loop over a complex object? either JSON or array?
If so, is there any example on getting this to work? 

Otherwise, only way to get a loop would be to have this in .NET: deserialize the JSON into a .NET ienumerable & loop in .NET and call a prompt template for each element...

**Comment by teresaqhoang** [comment]
Will test both `#each` and `array` tomorrow

**Comment by teresaqhoang** [comment]
It seems #each and array are both working as expected. Closing this as resolved. 



> hi @markwallace-microsoft is there any way to have the handlebars process a loop over a complex object? either JSON or array? If so, is there any example on getting this to work?
> 
> Otherwise, only way to get a loop would be to have this in .NET: deserialize the JSON into a .NET ienumerable & loop in .NET and call a prompt template for each element...

@joslat HB has built in support for looping over objects using `#each` https://handlebarsjs.com/guide/builtin-helpers.html#each. 
>  for object iteration, {{@key}} references the current key name:
```handlebars
{{#each object}} {{@key}}: {{this}} {{/each}}
```
