### ISSUE TITLE
Python: TypeError - Can't instantiate abstract class AstraDBMemoryStore with abstract methods

### ISSUE THREAD

**Issue by david-polo** [microsoft/semantic-kernel#5092]
**Describe the bug**
I tried to use AstraDBMemeoryStore as a memory store of sematic kenel.
But it says AstraDBMemoryStore is abstract class.

TypeError: Can't instantiate abstract class AstraDBMemoryStore with abstract methods create_collection, delete_collection, does_collection_exist, get, get_batch, get_collections, get_nearest_match, get_nearest_matches, remove, remove_batch, upsert, upsert_batch

**To Reproduce**
```
from semantic_kernel.connectors.memory.astradb import (
    AstraDBMemoryStore,
)

memory_store = AstraDBMemoryStore(
        astra_application_token,
        astra_id,
        astra_region,
        keyspace_name,
        vector_size,
        "cosine",
)
```

**Expected behavior**
It should work.

**Comment by david-polo** [comment]
@eavanvalkenburg , could you help me?

**Comment by moonbox3** [comment]
That error is occuring because Python is telling you that you haven't implemented the required abstract methods/properties. If you look at `MemoryStoreBase` you will see methods like: `get_collections`, `delete_collections`, `does_collection_exist`. Your code has the *_async suffix on all method names. It doesn't look like you got latest code after we performed the name update -- I remember your PR was open for a bit of time. 

Please simply remove the _async suffix from all method names and the issue should be resolved.
