### ISSUE TITLE
.Net: Consider ImageContent and AudioContent inherit from BinaryContent

### ISSUE THREAD

**Issue by SergeyMenshykh** [microsoft/semantic-kernel#5262]
@matthewbolanos please provide details of the issue that would be fixed by the change.

**Comment by Krzysztof318** [comment]
@SergeyMenshykh I don't think it will be good. BinaryContent.Data is required but ImageContent.Data and AudioContent.Data are optional, so casting these two to BinaryContent would give inconsistent behavior. Following this way, we should create a DataKernelContent class with Uri and BinaryData parameters and inherit from it.

**Comment by matthewbolanos** [comment]
This feature should be worked on in conjunction with https://github.com/microsoft/semantic-kernel/issues/5263 (which should address @Krzysztof318's concerns around BinaryContent.Data being required). Because `BinaryContent` could/should be hydrated with either a URL or a byte array, it should likely be renamed to `FileContent`.

The main scenario that we'd like to support is the following...

### Context
- Today, the `BinaryContent` class is predominantly used for the Assistants API
- The Assistants API supports several different file types: https://platform.openai.com/docs/assistants/tools/supported-files
- Most notably, it supports image types like jpg and png
- In the future, it may also support other types like audio and video

### Scenario
- The user makes a request to the Assistant API
- The Assistant API returns back with an image
- The developer then wants to take the image and run it through another model (e.g., image-to-text to get a description for it for a11y)
- Instead of taking the binary of the file and creating a new `ImageContent` with it, the user should simply be able to cast it to the correct type.

**Comment by matthewbolanos** [comment]
As a test of the new hierarchy, the following POC should be possible:

1. Ask an agent built with the Assistant API with Code Interpreter to create an 1) image, 2) audio file, and 3) word file
2. Get the collection of files from the `ChatMessageContent`
3. Save all the files to disk using the parent class (e.g., `BinaryContent` or `FileContent`)
4. Type caste the image to `ImageContent` to perform a text-to-image task
5. Type caste the audio to `AudioContent` to perform audio-to-text task

**Comment by markwallace-microsoft** [comment]
Done
