### ISSUE TITLE
.Net: Rationalize how SK content types work

### ISSUE THREAD

**Issue by SergeyMenshykh** [microsoft/semantic-kernel#5263]
Rationalize how our content types work when they could be either given a reference (e.g., URI to generated resource) or binary.
The content should be able to be populated by either (reference or binary) and then be usable throughout the rest of the system. This should be an exit criteria for making these non-experiemental

**Comment by matthewbolanos** [comment]
- There are two ways that binary/file content can be provided to the Semantic Kernel: URIs or binary data.
- Depending on the model that Semantic Kernel interfaces with, Semantic Kernel must either provide a URI or binary data

This means there are four scenarios that we'd need to support:
- If a user creates a binary/file content object with a *URL*, then they should be able to use a model that accepts a *URL*.
- If a user creates a binary/file content object with a *byte array*, then they should be able to use a model that accepts a *byte array*.
- If a user creates a binary/file content object with a *URL*, then they should be able to use a model that accepts a *byte array*. In this scenario, Semantic Kernel should automatically download the file using the URL, convert it to a byte array, and then send it to the model.
- *[in the future future (i.e., not now)]* If a user creates a binary/file content object with a *byte array*, then they should be able to use a model that accepts a *URL*. In this scenario Semantic Kernel should be able to connect with a file store to create a publicly addressable URL for some content that could be sent to the model. In the short term, we can throw a "not supported" error message. Today, there are models like [Midjourney](https://docs.midjourneyapi.io/midjourney-api/midjourney-api/upload-image) and the Assistants API that support file upload capabilities

We will also need to rationalize the streaming versions in a similar way. Each of the four following scenarios should be supported.
- If a model streams a binary/file content object with multiple *URLs* for progressive renderings (e.g., a stable diffusion service that sends a URL for incremental image generations), then they should be able to access the image(s) via a *URL* to show the updates
- If a model streams a binary/file content object with a *byte array* for streaming content (e.g., audio and video), then they should be able to access the resources(s) via a *byte array* to stream the response
- If a model streams a binary/file content object with multiple *URLs* for progressive renderings (e.g., a stable diffusion service that sends a URL for incremental image generations), then they should be able to access the image(s) via a *byte array* to show the updates
- *[in the future future (i.e., not now)]* If a model stream a binary/file content object with a *byte array*, then they should be able to access the finished result via a URL so it can be sent to another model. In the short term, we can throw a "not supported" error message.

For the streaming scenarios, it should also be relatively easy way for a user to access the final/full binary/file content so that it can be saved.
