### ISSUE TITLE
.Net Purpose of HttpOperationException instead using HttpRequestException 

### ISSUE THREAD

**Issue by Krzysztof318** [microsoft/semantic-kernel#5404]
I wonder why SK has special exception to indicate http failure.
It requires knowledge from SK consumer to catch the right exception (if not catching general "Exception").

I think there is also possibility in the SK code, that someone forgot translates exception, so SK consumer should always check both HttpOperationException and HttpRequestException.

**Comment by SergeyMenshykh** [comment]
One of the reasons for having the HttpOperationException is to preserve as much detail as possible about exceptions which otherwise would not be possible. For example, HttpRequestException in .NET Standard 2.0 does not have a StatusCode property, which might be useful to the SK consumer, in addition to response content that is not provided by HttpRequestException by default. This content is read and included in HttpOperationException so that the consumer can obtain more details about what has occurred.  
   
Another reason for the exception is to abstract the SK consumer from the fact that an HTTP failure can be communicated by different exception types - HttpRequestException is thrown by connectors using HttpClient, and RequestFailedException is thrown by connectors using Azure.OpenAi SDK. Otherwise, SK consumer code would have to write a catch block for each exception type.

**Comment by Krzysztof318** [comment]
@SergeyMenshykh Thanks for clarification, closing.
