### ISSUE TITLE
.Net: Handle expired runs / Retry in Agent ChatRuns 

### ISSUE THREAD

**Issue by erjadi** [microsoft/semantic-kernel#5449]
Like many people I've been experiencing general flakiness of Assistants API in longer running processes, where the run will just not come back with a response. Now it might be debatable whether we need to "fix" this kind of unreliability in SK, but it might be something to consider.

The issue I've been having is that Assistant runs will get stuck in "in progress" for a long time, before ultimately timing out into an "expired" state. 

![OpenAI run lifecycle diagram](https://cdn.openai.com/API/docs/images/diagram-1.png)

In SK I noticed that [we are only checking for failed state](https://github.com/microsoft/semantic-kernel/blob/0636b1706134c3a839c7af2ab5cbfb4ba21784cd/dotnet/src/Experimental/Agents/Internal/ChatRun.cs#L78) and I would propose checking for expired state as well.
This would be a quick fix for the immediate problem of getting stuck.

For a larger feature request I am wondering if it's possible to save and restore state of a running multi-agent multi-turn solution somehow. The biggest issue with getting stuck on one of the agent runs is not just that it gets stuck, but that we lose the threads and work that has been done so far. Being able to continue from where we left off would be a welcome feature.

**Comment by markwallace-microsoft** [comment]
@crickman could you take a look at this issue.

**Comment by crickman** [comment]
@erjadi - Thanks for this clear analysis.  We can definately fill-out the run states as an immediate response.

In terms of continuing with a thread, have you tried `IAgent.GetThreadAsync()`?
https://github.com/microsoft/semantic-kernel/blob/main/dotnet/src/Experimental/Agents/IAgent.cs#L91

Aside: As you probably already know, Open AI has made the Run a one-time operation.  Retrying a failed run means initiating a new run.  Since this could have side effects for tooling scenarios, I've avoided adding a blind retry on run failure.

**Comment by crickman** [comment]
Calendar yesterday was on the stacked side (limited coding/focus opportunies), but noodling in this branch:

https://github.com/microsoft/semantic-kernel/tree/fix_agentstates

Starting functional validation / testing now...open to any feedback.

**Comment by crickman** [comment]
FYI - https://github.com/microsoft/semantic-kernel/pull/5486 (related, but separate)

**Comment by erjadi** [comment]
Sorry I was away for a bit, awesome work & quick turnaround @crickman
