### ISSUE TITLE
.Net: Auto Function Calling Bad Request Message Not Included in Tool Response

### ISSUE THREAD

**Issue by bmtreuherz** [microsoft/semantic-kernel#5541]
**Describe the bug**
We are using Open API style plugins with automatic function calling. When our APIs return 400 (Bad Request), we include descriptive messages in the response which can be very helpful in directing the LLM to self-correct mistakes (or more effectively prompt the user for additional clarification). This was a behavior which we observed in the SK V0 Stepwise Planer, but it appears that with automatic function calling, only the status code is included in the tool response. This means that the LLM will NOT see the message included with the bad request response, missing out on valuable details. See screenshot below. 

**To Reproduce**
1. Import a plugin to the kernel (i.e. `kernel.ImportPluginFromOpenApiAsync`). 
2. For the sake of repo, you can create simple API that returns a bad request with a message.
3. Invoke chat completions with automatic function calling. We happen to be using streaming `chatCompletion.GetStreamingChatMessageContentsAsync(chatHistory, settings, kernel);`
4. Observe the chat history after invocation. You will see that the bad request message is not included and generic error message has been logged in the tool response. 

**Expected behavior**
We would expect that the full response (i.e. status code and response content/ message) would be included in the Tool response message. 

**Screenshots**
![image](https://github.com/microsoft/semantic-kernel/assets/8550902/2657855b-f014-49dd-be7c-5d09628ea9f7)

**Platform**
 - OS: Windows
 - IDE: Visual Studio
 - Language: C#
 - Source: Nuget Package 1.3.1

**Comment by tdashworth** [comment]
Hi, I had the same issue. SK version 1.6. GPT-4, Auto Function calling and streaming. 

I narrowed down the issue to (here)[https://github.com/microsoft/semantic-kernel/blob/7fd2ac3dad87b914eed037850593740b9e2e1685/dotnet/src/Connectors/Connectors.OpenAI/AzureSdk/ClientCore.cs#L1012] where the `Id`, `Name`, and `Arguments` properties could not be found. This was because I persisted the chat history into CosmosDB and then recreated the history every time. I selected "CamelCase" naming conversation which broke this parsing. 

To fix this, I parsed the `JsonObject` myself which skipped the code linked above. 

It would be good to make this parsing case insensitive if possible.

**Comment by matthewbolanos** [comment]
Thanks for sharing. We're currently updating our filters so that they can allow developers to override / customize the error and cancelation messages for the LLM. We expect this to land in the next week or two. At that time, we'll provide documentation on how you can address this need.

**Comment by dmytrostruk** [comment]
> We're currently updating our filters so that they can allow developers to override / customize the error and cancelation messages for the LLM.

PR for this functionality is here: https://github.com/microsoft/semantic-kernel/pull/5671
