### ISSUE TITLE
.Net: Using a custom LLM for memories to establish a link between the document and the custom LLM

### ISSUE THREAD

**Issue by Syed-21** [microsoft/semantic-kernel#5597]
I searched alot but in vain, the feature that i would like is that uptil now if we use memories of semantic kernel it uses openai or azure service but what if we wanted to use memories with a model that has been downloaded or either with LMStudio. So that whenever a document is uploaded through "importDocumentAsync" and when the user asks a question the response should come from the document through the local model not through azure or openai service , also the embeddings should be generated by a local model that is downloaded.

**Comment by dluc** [comment]
@markwallace-microsoft I've implemented this in KM if someone wants to port the code to SK, the relevant code change can be found here https://github.com/microsoft/kernel-memory/pull/380

**Comment by markwallace-microsoft** [comment]
@RogerBarreto could you look at the "embeddings should be generated by a local model" aspect of this issue.

**Comment by DrappierTechnologies** [comment]
Like Syed, I've searched a lot on this topic as well and just happened to find this issue in the Discord. I see that this issue has hit the backlog so I'm expecting to have to build in the meantime that can handle memories. Before I start down the path of a "side-loaded" local semantic memory implementation I just wanted to confirm my understanding of a few things here:

1. `MemoryBuilder ` will not work without a text-embedding model
2. The text-embedding models in Semantic Kernel are limited to Azure or OpenAI services
3. Using anything outside the two services above will not function with Semantic Kernel and must be manually implemented as a function or plugin for use by an Agent or within a Planner.

The reason I ask confirmation is because I'm currently overriding the `AddOpenAIChatCompletion` in the `KernelBuilder` with a `DelegatingHandler` and a local OpenAI API but it doesn't seem like an override would be possible in this context and I would just have to build something to side load into a function/plugin for my Agent.
