### ISSUE TITLE
.Net: Default values specified for Query params in OpenAPI spec is not used for making REST API calls using RestApiOperationRunner

### ISSUE THREAD

**Issue by utbose** [microsoft/semantic-kernel#5864]
**Describe the bug**
Currently in openAPI spec if the value of a query parameter (of a url) is not sent as arguments from caller, the query parameters are completely dropped even if they have specified default values in the openAPI schema.

This change will help assign default values that is specified in openAPI schema to parameter objects if no arguments are provided from the caller. Without this change we wont be able to support urls which has default query parameters.

**To Reproduce**
Consider the following example snippet of an openAPI spec:
```
"parameters": [
                    {
                        "in": "query",
                        "name": "outputTypes",
                        "schema": {
                            "type": "string",
                            "default": "MakeVideoPluginOutputAnnotation"
                        },
                        "description": "description of outputTypes"
                    }
               ]
```

If we use the semantic kernel openAPI extension package (`microsoft.semantickernel.plugins.openapi`) from any app to parse an openAPI spec and execute a REST API call, the REST API url generation logic does not use the default value specified in the schema (shown above) to populate the query parameters when there are no values specified by the caller for those query parameters. Even though The `RestApiOperationParameter` object parses the default value and stores it as a member variable ([here](https://github.com/microsoft/semantic-kernel/blob/62cc40d063708befd0a6a8062676bfd12c6ca65b/dotnet/src/Functions/Functions.OpenApi/Model/RestApiOperationParameter.cs#L53)), it is not used to populate the query parameters when arguments are not specified. The following [pull request](https://github.com/microsoft/semantic-kernel/pull/5863) is a very small change to fix the issue.

**Expected behavior**
When the query parameters cannot be populated from the arguments set by the caller, set the default values if specified in the openAPI schema.

**Screenshots**
N/A

**Platform**
 - OS: [Windows]
 - IDE: [Visual Studio]
 - Language: [C#]
 - Source: [(https://github.com/microsoft/semantic-kernel)]

**Additional context**
This package is currently used by AI orchestrator for invoking plugins functions specified by plugin owners as openAPI spec. Our platform is a plugin hosting platform where we have this requirement to use the default values of query params when not specified by caller arguments to enable the execution of the plugin functions.

PR link: https://github.com/microsoft/semantic-kernel/pull/5863

**Comment by SergeyMenshykh** [comment]
Thanks @utbose, for reporting the issue. 

Based on our previous conversation and according to the OpenAPI specification, the default value for an optional parameter is not required to be passed by the client to the server. The server should use the default value specified on the server side if the client does not provide any value.

<img width="490" alt="image" src="https://github.com/microsoft/semantic-kernel/assets/68852919/c79a1bb2-7a29-471c-8ef9-a24382cfc57d">

Source - https://swagger.io/docs/specification/describing-parameters/

So, the correct solution for the issue would be to contact the API owners and ask them to align their API with the OpenAPI specification to support the default value server-side or to mark that parameter as required (currently, it's optional) so that it must be provided. However, as far as I understand, it's not just one API that behaves like this, and it's not feasible to change all of them. If that's the case, you can always access the parameter's default value in your code via the function metadata property and use it if no argument is provided for the parameter:

![image](https://github.com/microsoft/semantic-kernel/assets/68852919/4ff50f76-8a27-4947-89a2-6c65b119fde9)

**Comment by utbose** [comment]
@SergeyMenshykh - We would want these values to passed to the calling site as part of the REST API call. Can you provide some more details about how we can do that using this metadata property ? May be some example would help.

**Comment by SergeyMenshykh** [comment]
Closing the issue because a workable solution for using and accessing default values of parameters has been provided.
