### ISSUE TITLE
.Net: In IAutoFunctionInvocationFilter setting AutoFunctionInvocationContext.Terminate to true adds an empty assistant message to the chat history

### ISSUE THREAD

**Issue by EdenTanami** [microsoft/semantic-kernel#6064]
Adding AutoFunctionInvocationFilter to the kernel that calls await next (invoke the next filter/the actual function) and then set AutoFunctionInvocationContext.Terminate to true causes the addition of empty assistant message to the end of the chat history.

**To Reproduce**
1. Add to the kernel the following IAutoFunctionInvocationFilter - 
![image](https://github.com/microsoft/semantic-kernel/assets/160887465/cf7f00ab-eb3c-474e-acf6-d17a6451f56d)
2. Run the auto chat completion with user prompt that causes some function invocation.
3. Observe the returned chat history and see that the last message (after the function result message) is an empty assistant message.
![image](https://github.com/microsoft/semantic-kernel/assets/160887465/9b0a17b1-b79f-40fb-8a7e-8845f21e71d6)

**Expected behavior**
For the integrity of the chat history (even upon termination) it makes sense to have assistant response after the function response. 
But empty one doesn't make much sense. 
Even when adding manually to the chat history informative assistant message (after setting the terminate flag to true in the IAutoFunctionInvocationFilter code) still the empty assistant message is being added.

**Platform**
OS: Windows
IDE: Visual Studio,
Language: C#
Source: SK NuGet package version 1.10.0

**Comment by dmytrostruk** [comment]
@EdenTanami Could you please share an example how you configure execution settings and start invocation?

I'm trying to reproduce this, and in my case last message in chat history is function result with `tool` role:
![image](https://github.com/microsoft/semantic-kernel/assets/13853051/9ee20e91-eae5-42eb-847b-e197c0e4b798)

**Comment by EdenTanami** [comment]
@dmytrostruk thanks for the quick response!
Regarding the execution settings - i set the temperature to 0 and i used ToolCallBehavior.EnableFunctions with subset of the kernel's plugins and with true in the autoInvoke. (other than that its the default settings).
and i am calling AzureOpenAIChatCompletionService.GetStreamingChatMessageContentsAsync with those settings

**Comment by EdenTanami** [comment]
Tried the none streaming GetChatMessageContentsAsync and got other results - 
Not an empty assistant message but the tool result message appears twice 
![image](https://github.com/microsoft/semantic-kernel/assets/160887465/eaee54b0-f4b2-43d5-821e-549508c20913)

![image](https://github.com/microsoft/semantic-kernel/assets/160887465/f4898782-bc2d-4896-868e-a321b21d4edb)

**Comment by EdenTanami** [comment]
one last comment- 
in the none streaming GetChatMessageContentsAsync that adds only tools messages i get exception when appending another user message to the history - that assistant response is required after tool message
![image](https://github.com/microsoft/semantic-kernel/assets/160887465/7637729b-e4cb-4064-ba23-263dcafa5052)

**Comment by dmytrostruk** [comment]
> @dmytrostruk thanks for the quick response!
> Regarding the execution settings - i set the temperature to 0 and i used ToolCallBehavior.EnableFunctions with subset of the kernel's plugins and with true in the autoInvoke. (other than that its the default settings).
> and i am calling AzureOpenAIChatCompletionService.GetStreamingChatMessageContentsAsync with those settings

@EdenTanami Followed the same approach and last chat history is still `tool` result with value that my function returned:
![image](https://github.com/microsoft/semantic-kernel/assets/13853051/d65075ae-8e32-4424-82ea-93ddbe8e1d12)

I also tried with multiple functions to be invoked, and still - filter terminates the operation as needed. I'm wondering if there is anything else that's different in your scenario? For example, can you try the code that I shared, apply it in your environment and see if it works? If yes, are there any differences with your code? Also, make sure your filter is registered and you set `context.Terminate = true`. We have `LogDebug` when we are terminating execution, so if you have logging attached with `LogLevel.Debug`, then you should see termination log message in your logs.

> Tried the none streaming GetChatMessageContentsAsync and got other results -
> Not an empty assistant message but the tool result message appears twice

Can you check 3rd message where LLM replied with tool calls and see if it didn't request to call this function twice? If that's not the case, can you remove all filters and see if it can be reproduced?

> one last comment-
> in the none streaming GetChatMessageContentsAsync that adds only tools messages i get exception when appending another user message to the history - that assistant response is required after tool message

If you want to terminate early and you want to use the same chat history for subsequent requests, in this case instead of terminating you can skip function execution by _not_ calling `await next(context)`. In this case, your next functions won't be invoked but chat history will be populated with empty tool responses, which is required for each tool request by LLM in chat history.

**Comment by EdenTanami** [comment]
@dmytrostruk Found that we had some assumptions on the chat completion's response we get which was not correct in this use case.
Usually we were adding the returned messages to the chat history that was sent to the call.
In the none streaming call upon termination we get back the tool response and it is also added to the chat history (which caused the duplication in our side.
Without the termination the response contains just the assistant msg and the tools are only added to the history).

I'm sorry for the confusion and thanks for your help!

**Comment by dmytrostruk** [comment]
@EdenTanami It sounds like it's working as expected. I'm going to close this issue, feel free to open a new one in case you notice some problems. Thanks for your insights!
