### ISSUE TITLE
Python: Validate plugin names are unique?

### ISSUE THREAD

**Issue by stefan521** [microsoft/semantic-kernel#6383]
I could define completely different kernel plugins and if I register them with the same name then the last one that gets registered wins. That's because the kernel plugins are a dictionary. Should there be some validation when plugins are added to the kernel to check if there's already a plugin with that name?

Consider the scenario where someone adds a plugin name that should be reserved, such as `UserInteraction`, which is used to report the final answer via `UserInteraction-SendFinalAnswer`. Stuff would break.

I'm happy to implement this if the maintainers consider it a good idea.

**Comment by stefan521** [comment]
.NET does verify it here: https://github.com/microsoft/semantic-kernel/blob/main/dotnet/src/InternalUtilities/src/Diagnostics/Verify.cs#L87

```c#
if (plugins is not null && plugins.Contains(pluginName))
{
     throw new ArgumentException($"A plugin with the name '{pluginName}' already exists.");
}
```

I'll open a PR shortly.

**Comment by moonbox3** [comment]
Stating here the same comment left in the PR: This was by design since [plugins](https://github.com/microsoft/semantic-kernel/blob/246b84357ff6e0415fe5cb7fd97b622fb9bc9032/python/semantic_kernel/functions/kernel_function_extension.py#L34) are a Python dictionary, and by default in Python, dictionaries overwrite an existing key if the same key is added.
