### ISSUE TITLE
Python: A way to surpress the Could not parse prompt (prompt text) as xml, treating as text warning

### ISSUE THREAD

**Issue by wu-hongjun** [microsoft/semantic-kernel#6651]
Hello all,

Some of my prompt that I saved in skprompt.txt (I am running on Python) will make SK throw the follow warning:

```
Could not parse prompt (prompt) as xml, treating as text
```

And I can't seem to find a way to suppress this error. I don't intend to load the skprompt.txt as xml, and this is logging a lot of text in my logs. How to surpress it?

**Comment by eavanvalkenburg** [comment]
@wu-hongjun it is a info message, so you could just make sure that you have loglevel set higher then that, but it does make me wonder what you have in your prompt, because we do use an internal xml structure in order to allow a lot of flexibility for the developer, while being able to accurately move things like a chat_history between runs and models, see this post for more details: https://devblogs.microsoft.com/semantic-kernel/enhanced-templating-in-semantic-kernel-for-python/
