### ISSUE TITLE
Python: Update Azure AI Search Memory Connector with New Text Search Design

### ISSUE THREAD

**Issue by alliscode** [microsoft/semantic-kernel#6832]
Text Search ADR is here: https://github.com/microsoft/semantic-kernel/issues/5799

 Implement new abstractions
 Unit tests
 Integration tests
 Document any limitations in the implementation
 Implement a basic RAG samples
 Work with Sofia on a new Blog post
 Obsolete the old implementation
 Create task to graduate the Text Search Service

**Comment by jamesmkfoo23** [comment]
Hi, not sure if this should be relevant here.

ACS/Az AI Search memory connector search function is unable to work because of some hardcoded schema (eg: Id field). This issue is described here https://github.com/microsoft/semantic-kernel/issues/2492

and code reference: python/semantic_kernel/connectors/memory/azure_cognitive_search/utils.py

Can the search fields and parameters be parameterized somehow?
