### ISSUE TITLE
.Net: Bug: AgenGroupChat  yields function response messages when it shouldn't

### ISSUE THREAD

**Issue by EdenTanami** [microsoft/semantic-kernel#7075]
**Describe the bug**
According to the code of the AgenGroupChat's  base abstract class - AgentChat, the group chat InvokeAsync should add to the History all the messages yielded by the agent and return to its caler only the assistant response (not tools related messages).
In practice, calling agentGroupChat.InvokeAsync returns both the final assistance response and the messages with tool role.

I reviewed the AgentChat code and saw that the condition of the returned messages is:
![image](https://github.com/microsoft/semantic-kernel/assets/160887465/57ba72d2-5745-47b3-807a-759e1f292ec4)
The if condition might be the problem - I saw that in my function response message there are 2 items, one isn't from the mentioned types-
![image](https://github.com/microsoft/semantic-kernel/assets/160887465/4adbff44-cda7-47aa-bff4-c93e78aa0f60)

**To Reproduce**
1. Create an agent (ChatCompletionAgent) with kernel that contains plugin.
2. Add the agent to a group chat.
3. Add to the groupChat history user message that will trigger the the plugin.
4. call the groupChat.InvokeAsync() 
5. See the tool message that returns.

**Expected behavior**
Only final assistant response returns from the groupChat InvokeAsync.

**Screenshots**
![image](https://github.com/microsoft/semantic-kernel/assets/160887465/51baeaa7-3a7a-402d-85e0-2a58309231c2)

![image](https://github.com/microsoft/semantic-kernel/assets/160887465/ff308322-027e-47fa-9ca0-18494e038e27)

**Platform**
OS: Windows
IDE: Visual Studio,
Language: C#
Source: SK NuGet package version 1.15.0

**Comment by crickman** [comment]
I believe you'll find this issue has been resolved as part of:

https://github.com/microsoft/semantic-kernel/pull/6956

We are publishing a new nuget package today.  Can you please retry and verify the current result?

I do see the original root cause here:

https://github.com/microsoft/semantic-kernel/blob/main/dotnet/src/Connectors/Connectors.OpenAI/AzureSdk/ClientCore.cs#L1454

(Unclear why this wasn't visible in the sample originally.  I'd certainly expect the identical result.)
