### ISSUE TITLE
.Net: Implement and update RAG samples

### ISSUE THREAD

**Issue by markwallace-microsoft** [microsoft/semantic-kernel#7350]
- [ ] Create a basic RAG sample
- [ ] Update existing RAG samples to use the new abstractions

**Comment by rahulmansharamani14** [comment]
Hi @markwallace-microsoft, @evchaki, @westey-m,

I'm interested in taking on this issue to implement basic RAG samples. Since there’s no description provided, could you clarify what specific functionality or structure you’re looking for in the samples? 

For context, I’ve worked with the Semantic Kernel in .NET before and would love to contribute here. Any additional guidance would be appreciated!

Thank you!
