### ISSUE TITLE
.Net: The class implementing IPromptRenderFilter is not being called

### ISSUE THREAD

**Issue by takashiuesaka** [microsoft/semantic-kernel#7375]
The class implementing IPromptRenderFilter is not being called when using the ChatCompletionService.GetChatMessageContentAsync method.

Program.cs
```csharp
var MODEL_ID = Environment.GetEnvironmentVariable("MODEL_ID");
var API_KEY = Environment.GetEnvironmentVariable("API_KEY");
var ENDPOINT = Environment.GetEnvironmentVariable("ENDPOINT");

var builder = Kernel.CreateBuilder()
    .AddAzureOpenAIChatCompletion(
        deploymentName: MODEL_ID,
        endpoint: ENDPOINT,
        apiKey: API_KEY
        );

LoggerFactory loggerFactory = new();

var logger = loggerFactory.CreateLogger<Program>();
builder.Services.AddLogging(services => services.AddConsole().SetMinimumLevel(LogLevel.Trace));

builder.Services.AddSingleton<IPromptRenderFilter>(new PromptRenderFilter(logger));

Kernel kernel = builder.Build();

#pragma warning disable SKEXP0050
kernel.Plugins.AddFromType<TimePlugin>("time");

var chatCompletionService = kernel.GetRequiredService<IChatCompletionService>();

OpenAIPromptExecutionSettings openAIPromptExecutionSettings = new()
{
    ToolCallBehavior = ToolCallBehavior.AutoInvokeKernelFunctions
};

var result = await chatCompletionService.GetChatMessageContentAsync(
    "Is {{ time.Date }}, a national holiday in Japan?",
    executionSettings: openAIPromptExecutionSettings,
    kernel: kernel);

Console.WriteLine(result.ToString());
```

PromptRenderFilter.cs
```csharp
internal class PromptRenderFilter(ILogger logger) : IPromptRenderFilter
{
    public async Task OnPromptRenderAsync(PromptRenderContext context, Func<PromptRenderContext, Task> next)
    {
        await next(context);

        logger.LogInformation($"RenderdPrompt: {context.RenderedPrompt}");
    }
}
```

I confirmed that the class implementing IAutoFunctionInvocationFilter is called when using the ChatCompletionService.GetChatMessageContentAsync method.

I know that implementing it in the following way works well. However, I don't think this approach is ideal.

```csharp
//var result = await chatCompletionService.GetChatMessageContentAsync(
//    "Is {{ time.Date }}, a national holiday in Japan?",
//    executionSettings: openAIPromptExecutionSettings,
//    kernel: kernel);

var semanticFunction = kernel.CreateFunctionFromPrompt(
            "Is {{ time.Date }}, a national holiday in Japan?", openAIPromptExecutionSettings);

var result = await kernel.InvokeAsync(semanticFunction);

```

Is this a bug or just unimplemented?

**UPDATE**
I also confirmed that the event handler added using the addPromptRenderedHook function in the Java SDK is not called when using ChatCompletionService.getChatMessageContentAsync.

**Comment by dmytrostruk** [comment]
@takashiuesaka When you pass prompt in chat completion service like this:
```csharp
var result = await chatCompletionService.GetChatMessageContentAsync(
    "Is {{$date}}, a national holiday in Japan?",
    executionSettings: openAIPromptExecutionSettings,
    kernel: kernel);
```
prompt rendering operation is not performed, and your prompt is injected into chat history as it is:
https://github.com/microsoft/semantic-kernel/blob/12a877b8297bfb39987843b3f95acf606cb163ca/dotnet/src/SemanticKernel.Abstractions/AI/ChatCompletion/ChatCompletionServiceExtensions.cs#L42-L45

That's why `IPromptRenderFilter` is not invoked. So, in order to invoke `IPromptRenderFilter`, prompt rendering operation should be performed, and this operation is performed only when there is a prompt function defined and executed, as per your example:
```csharp
var semanticFunction = kernel.CreateFunctionFromPrompt(
            "Is {{$date}}, a national holiday in Japan?", openAIPromptExecutionSettings);

var result = await kernel.InvokeAsync(semanticFunction);
```

So, the real question is - should we add prompt rendering operation when calling `IChatCompletionService` directly? I would suggest creating a new issue for it with described use-cases, pros and cons of this approach etc, so it can be discussed further. In this case, we can close this issue, because if we will add prompt rendering operation to `IChatCompletionService` at some point, then, as part of this task, we will have to add `IPromptRenderFilter` invocation as well. 

Thank you!

**Comment by takashiuesaka** [comment]
@dmytrostruk Thank you for your response. I understand that I need to create a new issue. So, I will create a new one and close this issue.

**Comment by takashiuesaka** [comment]
@dmytrostruk Thank you for your response. I understand that I need to create a new issue. So, I will create a new one and close this issue.

**Comment by takashiuesaka** [comment]
I created a discussion #7403.
