### ISSUE TITLE
Python: Using FunctionChoiceBehavior.Required in Python gets an invalid value error

### ISSUE THREAD

**Issue by sophialagerkranspandey** [microsoft/semantic-kernel#7463]
### Discussed in https://github.com/microsoft/semantic-kernel/discussions/7410

<div type='discussions-op-text'>

<sup>Originally posted by **leeprtc** July 23, 2024</sup>
Does FunctionChoiceBehavior.Required work in Python?

I tried running the function_calling_with_required_type.py sample. Instead of using OpenAI, I'm using Azure OpenAI so I swapped OpenAIChatCompletion and OpenAIChatPromptExecutionSettings with AzureChatCompletion and AzureChatPromptExecutionSettings. However, when I ran this sample, I'm getting the following error with both the v1.2.0 and v1.3.0 packages. The model I'm using is GPT-4o version 2024-05-13.

```
  File "C:\...\anaconda3\envs\AI\Lib\site-packages\semantic_kernel\connectors\ai\open_ai\services\open_ai_chat_completion_base.py", line 252, in _send_chat_stream_request
    response = await self._send_request(request_settings=settings)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\...\anaconda3\envs\AI\Lib\site-packages\semantic_kernel\connectors\ai\open_ai\services\open_ai_handler.py", line 51, in _send_request
    raise ServiceResponseException(
semantic_kernel.exceptions.service_exceptions.ServiceResponseException: ("<class 'semantic_kernel.connectors.ai.open_ai.services.azure_chat_completion.AzureChatCompletion'> service failed to complete the prompt", BadRequestError('Error code: 400 - {\'error\': {\'message\': "Invalid value: \'required\'. Supported values are: \'none\' and \'auto\'.", \'type\': \'invalid_request_error\', \'param\': \'tool_choice\', \'code\': \'invalid_value\'}}'))
```
</div>

**Comment by moonbox3** [comment]
@leeprtc, thanks for bringing this up. It looks like Azure OpenAI doesn't have the same functionality as OpenAI regarding the `required` type (OpenAI docs: https://platform.openai.com/docs/guides/function-calling/function-calling-behavior). OpenAI now supports multiple `required` tools, instead of just one.

@sarah-widder, when we're submitting to `tool_choice` as `required`, we're getting a 400:

```
BadRequestError('Error code: 400 - {\'error\': {\'message\': "Invalid value: \'required\'. Supported values are: \'none\' and \'auto\'.", \'type\': \'invalid_request_error\', \'param\': \'tool_choice\', \'code\': \'invalid_value\'}}'))
```

I see the Azure OpenAI docs (https://learn.microsoft.com/en-us/azure/ai-services/openai/reference#chatcompletiontoolchoiceoption), the `required` type doesn't show as an allowed option. Is this support planned on your end, to match OpenAI's allowed choices?

**Comment by leeprtc** [comment]
@moonbox3  Just a FYI. Using the latest C# nuget, I was able to use ToolCallBehavior.RequiredFunction with the exact same model.

**Comment by moonbox3** [comment]
> @moonbox3 Just a FYI. Using the latest C# nuget, I was able to use ToolCallBehavior.RequiredFunction with the exact same model.

That's because it's mapping it to a single function like:

```
{"type": "function", "function": {"name": "my_function"}}
```
