### ISSUE TITLE
Python: New Feature: Anthropic AI connector for Python

### ISSUE THREAD

**Issue by andrewldesousa** [microsoft/semantic-kernel#7565]
Claude is a strong language model that many users would like to use for their application. If the SK team thinks this something that this is be valuable for semantic-kernel, I'd like to help by implementing this connector

**Comment by moonbox3** [comment]
Hi @andrewldesousa, we're tracking this via #6501. Feel free to pick up that item if you'd like. Since it's a big task, similar to what's been done for the MistralAI connector, it can be broken down into three parts: chat/text completions, embeddings, and function calling. Closing this item so we can track in 6501. You can add any comments there.
