### ISSUE TITLE
.Net: Bug: AzureCosmosDBNoSQLMemoryStore - CreateCollectionAsync results in 400 error

### ISSUE THREAD

**Issue by westdavidr** [microsoft/semantic-kernel#7584]
**Describe the bug**
Using `AzureCosmosDBNoSQLMemoryStore`,  the method `CreateCollectionAsync` results in a 400 error: 

> "Vector Indexing is not supported for shared throughput offer"

**To Reproduce**
Create `AzureCosmosDBNoSQLMemoryStore` instance and call `CreateCollectionAsync`

**Expected behavior**
Cosmos Collection should be created with proper vector support enabled

**Platform**
 - OS: Windows
 - IDE: VS
 - Language: C#
 - Source: 1.16.2

**Comment by westdavidr** [comment]
I'll add that this is attempting to create a new Container in an existing DB

**Comment by dmytrostruk** [comment]
@westdavidr Thanks for reporting this issue. 
Based on error message, it looks like you are facing a limitation from your created Azure CosmosDB for NoSQL database with shared throughput: 
https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/vector-search#current-limits-and-constraints
![image](https://github.com/user-attachments/assets/5b2ffd6d-5f9c-4387-aa77-5bd9c8115780)

In order to resolve it, I think you should uncheck following setting:
https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/how-to-provision-database-throughput?tabs=dotnetv2#provision-throughput-using-azure-portal
![image](https://github.com/user-attachments/assets/f8977ea0-14ab-440d-8912-c19bff2fe1e7)

Let us know if this helps to resolve your problem. Thanks a lot!

**Comment by westdavidr** [comment]
Thanks for the explanation. It makes sense now.
