### ISSUE TITLE
.Net: Bug: Unable to resolve dependency 'Azure.AI.OpenAI'. 

### ISSUE THREAD

**Issue by hailiang-shen** [microsoft/semantic-kernel#8069]
**Describe the bug**
I was following this article https://learn.microsoft.com/en-us/semantic-kernel/get-started/quick-start-guide?pivots=programming-language-csharp. I created a console application with .Net Framework 4.8 using Visual Studio.

**To Reproduce**
1. Go to 'Tools'
2. Click on 'Nuget Package Manager'
3. Click on Browse and search for 'SemanticKernel'
4. Install Microsoft.SemanticKernel to my project and see the error below

![image](https://github.com/user-attachments/assets/e211958a-47b2-4db2-ba7c-18afc55b4125)

**Platform**
 - OS: Windows
 - IDE: Visual Studio
 - Language: C#
 - Source: NuGet package version 1.17.1

**Comment by dmytrostruk** [comment]
@hailiang-shen Thanks for reporting this issue, I can reproduce it.
In order to resolve it, please try to install `Azure.AI.OpenAI` package separately:
1. Mark `Include prerelease` checkbox in `Nuget Package Manager` window.
2. Search for `Azure.AI.OpenAI` package.
3. Install version `1.0.0-beta.17`. 
4. When it's installed, try to install `Microsoft.SemanticKernel` version `1.17.1` again.

![image](https://github.com/user-attachments/assets/8d07ffac-da5d-4cc2-b504-3345e61155ff)

**Comment by dmytrostruk** [comment]
Update: Issue is not reproducible with .NET 8, only with .NET Framework 4.8.

**Comment by hailiang-shen** [comment]
Thank you @dmytrostruk, manually installing Azure.AI.OpenAI first worked.
