### ISSUE TITLE
.Net: Support for streaming response in Open API plugins

### ISSUE THREAD

**Issue by markwallace-microsoft** [microsoft/semantic-kernel#8070]
Build on this PR: https://github.com/microsoft/semantic-kernel/pull/7949

**Comment by FriedChickenOnTheWay** [comment]
Thank you very much @SergeyMenshykh and @markwallace-microsoft for supporting the streaming! 

I was reviewing the [PR ](https://github.com/microsoft/semantic-kernel/pull/8182) and had a question about this line: [RestApiOperationRunner.cs#L217](https://github.com/microsoft/semantic-kernel/blob/main/dotnet/src/Functions/Functions.OpenApi/RestApiOperationRunner.cs#L217). My understanding is that we should use the HttpCompletionOption.**ResponseHeadersRead** option rather than HttpCompletionOption.**ResponseContentRead** when we anticipate a Streaming response, otherwise it would still wait here until the streaming finishes, right? If this is the case, we won't have a complete support of streaming. 

But I may have missed something, please let me know if I am mistaken, thank!
