### ISSUE TITLE
.Net Bug: method not found error when using 1.18.* package

### ISSUE THREAD

**Issue by LittleLittleCloud** [microsoft/semantic-kernel#8318]
**Describe the bug**
version

(There are also indirect reference to `OpenAI 2.0.0-beta8` as well)
```
  <ItemGroup>
    <PackageReference Include="Microsoft.SemanticKernel" Version="1.18.0-rc" />
    <PackageReference Include="Microsoft.SemanticKernel.Connectors.AzureOpenAI" Version="1.18.0-rc" />
    <PackageReference Include="Microsoft.SemanticKernel.Agents.Core" Version="1.18.0-alpha" />
  </ItemGroup>
```
code
```csharp
var builder = Kernel.CreateBuilder()
    .AddAzureOpenAIChatCompletion(deploymentName, endpoint, key);


var kernel = builder.Build();

kernel.GetRequiredService<IChatCompletionService>();
```

stacktrace
```bash
  Message: 
System.MissingMethodException : Method not found: 'Void OpenAI.OpenAIClientOptions.set_ApplicationId(System.String)'.

  Stack Trace: 
AzureClientCore.GetAzureOpenAIClientOptions(HttpClient httpClient, Nullable`1 serviceVersion)
AzureOpenAIKernelBuilderExtensions.CreateAzureOpenAIClient(String endpoint, AzureKeyCredential credentials, HttpClient httpClient)
<>c__DisplayClass0_0.<AddAzureOpenAIChatCompletion>b__0(IServiceProvider serviceProvider, Object _)
<.ctor>b__0(IServiceProvider sp)
CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
ServiceProvider.GetService(Type serviceType)
ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
Kernel.GetRequiredService[T](Object serviceKey)
SemanticKernelAgentTest.BasicConversationTestAsync() line 40
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform**
 - OS: [e.g. Windows, Mac] Windows
 - IDE: [e.g. Visual Studio, VS Code] Visual Studio
 - Language: [e.g. C#, Python] C#
 - Source: [e.g. NuGet package version 0.1.0, pip package version 0.1.0, main branch of repository]

**Additional context**

**Comment by RogerBarreto** [comment]
Hi @LittleLittleCloud thanks for reaching out.

> There are also indirect reference to OpenAI 2.0.0-beta8 as well

Our projects use a [global versioning](https://github.com/microsoft/semantic-kernel/blob/c262d99ae3d62603463675510115751925e28f78/dotnet/Directory.Packages.props#L8) and we are not using any version override on the connectors and agent projects.

- [OpenAI Connector](https://github.com/microsoft/semantic-kernel/blob/c262d99ae3d62603463675510115751925e28f78/dotnet/src/Connectors/Connectors.OpenAI/Connectors.OpenAI.csproj#L38)
- [Azure OpenAI Connector](https://github.com/microsoft/semantic-kernel/blob/c262d99ae3d62603463675510115751925e28f78/dotnet/src/Connectors/Connectors.AzureOpenAI/Connectors.AzureOpenAI.csproj#L36) - Uses same references from OpenAI Connector.
- [Agents.OpenAI](https://github.com/microsoft/semantic-kernel/blob/c262d99ae3d62603463675510115751925e28f78/dotnet/src/Agents/OpenAI/Agents.OpenAI.csproj#L36)
- Agents.Core doesn't have any reference to OpenAI package.

Ensure you don't have any reference to the beta8 in your solution, otherwise during compilation this will override the ones used in the packages and create the conflict noted on this issue.
