### ISSUE TITLE
.Net: Bug: Kernel Filters don't invoke when using IChatCompletionService.GetStreamingChatMessageContentsAsync()

### ISSUE THREAD

**Issue by mornanate-1nebula** [microsoft/semantic-kernel#8389]
**Describe the bug**
I’ve encountered an issue with the GetStreamingChatMessageContentsAsync function in the ChatCompletionService. It appears that this function does not trigger any of the filters that have been registered, such as IFunctionInvocationFilter, IPromptRenderFilter, or IAutoFunctionInvocationFilter.

To troubleshoot, I tested the InvokePromptStreamingAsync function from the Kernel class. When using this function, all registered filters are correctly invoked, as expected. However, I prefer to use the ChatCompletionService for my implementation, which is where I’ve noticed this discrepancy.

Could you please clarify if the GetStreamingChatMessageContentsAsync function is supposed to support filter invocation? If it’s supposed to work, I might be configuring something incorrectly. Any guidance would be appreciated.

**Expected behavior**
When invoking the GetStreamingChatMessageContentsAsync function in the ChatCompletionService, any registered filters (such as IFunctionInvocationFilter, IPromptRenderFilter, or IAutoFunctionInvocationFilter) should be triggered automatically. 

These filters should apply their respective logic during the streaming of chat message contents, just as they do when using the InvokePromptStreamingAsync function from the Kernel class. This ensures consistency in behavior across different methods and allows for seamless integration of custom filter logic when using the ChatCompletionService.

**Platform**
 - OS: Windows
 - IDE: Visual Studio
 - Language: C#
 - Sources: Nuget Packages - Microsoft.SemanticKernel" Version="1.16.1"

**Comment by dmytrostruk** [comment]
@mornanate-1nebula Thanks for creating this issue! 
One important thing to remember when you use `GetStreamingChatMessageContentsAsync` from `ChatCompletionService` is to pass `Kernel` as a parameter, like this:
https://github.com/microsoft/semantic-kernel/blob/78289af2851a10b9f857051cb22bb00c7528f555/dotnet/src/IntegrationTests/Connectors/Google/Gemini/GeminiFunctionCallingTests.cs#L65-L66

In this case, filters should be triggered, since they are registered on `Kernel` level. If you already pass `Kernel` instance as a parameter and it still doesn't work, it would be great if you could share a code which reproduces this issue, so we can better understand the problem. Thanks a lot!
