### ISSUE TITLE
.Net: Inconsistent StopSequences Properties in PromptExecutionSettings classes

### ISSUE THREAD

**Issue by akordowski** [microsoft/semantic-kernel#8652]
In the [GeminiPromptExecutionSettings](https://github.com/microsoft/semantic-kernel/blob/cce877e591b18bb50c4ab6ccc6a7f2686a87454d/dotnet/src/Connectors/Connectors.Google/GeminiPromptExecutionSettings.cs#L113) and the [OpenAIPromptExecutionSettings](https://github.com/microsoft/semantic-kernel/blob/cce877e591b18bb50c4ab6ccc6a7f2686a87454d/dotnet/src/Connectors/Connectors.OpenAI/Settings/OpenAIPromptExecutionSettings.cs#L113) class the `StopSequences` property is defined as `IList<string>? StopSequences`.

But in the [HuggingFacePromptExecutionSettings](https://github.com/microsoft/semantic-kernel/blob/cce877e591b18bb50c4ab6ccc6a7f2686a87454d/dotnet/src/Connectors/Connectors.HuggingFace/HuggingFacePromptExecutionSettings.cs#L265C12-L265C30) and the [OllamaPromptExecutionSettings](https://github.com/microsoft/semantic-kernel/blob/cce877e591b18bb50c4ab6ccc6a7f2686a87454d/dotnet/src/Connectors/Connectors.Ollama/Settings/OllamaPromptExecutionSettings.cs#L50C12-L50C30) class the property is defined as `List<string>? Stop`.

It would be nice if the naming and the data type would be consistent through the `PromptExecutionSettings` classes. If wished I could provide PR for this issue. Thank you for consideration.

**Comment by RogerBarreto** [comment]
@akordowski I agree that we could use `IList<string>` for the `Stop` property in `HuggingFace`.

On the naming though, we have dedicated settings each provider uses a different name and since we are using specialized classes we try to be as coherent as possible to their documentation.

You may notice this also happening for names like `Top_P` that can be named as `Nucleus Sampling` depending on the provider. 

I hope though that the documentation (XmlDocs) of those properties make it clear the purpose of those properties.

I would be happy to accept a `PR` that improve the docs or updates the `List<string>` to `IList<string>` on hugging face connector.

Thanks for reaching out!
