### ISSUE TITLE
.Net: Bug: Using WithOpenAITextEmbeddingGeneration() with locally hosted model gives error "The input is not a valid Base64 string of encoded floats."

### ISSUE THREAD

**Issue by ChiragSoni95** [microsoft/semantic-kernel#8833]
**Describe the bug**
using WithOpenAITextEmbeddingGeneration(), I get the error "The input is not a valid Base64 string of encoded floats." in semantic kernel gives "The input is not a valid Base64 string of encoded floats."

**To Reproduce**
- See usage and error screenshots below

**Expected behavior**
Successfully get embedding and add to the MemoryStore

**Screenshots**

![image](https://github.com/user-attachments/assets/2253ba19-ff96-4104-a38f-54b2f84929a6)
![image](https://github.com/user-attachments/assets/a6a4a1d3-88b2-47a1-a4ad-7de37a7cbe5b)
![image](https://github.com/user-attachments/assets/41ff814b-fcc2-44a5-84e4-ed087758c641)

**Platform**
 - OS: Windows
 - IDE: VSCode
 - Language: C#

**Additional context**
I am using LMStudio for hosting a local embedding model, the precision value of floating point is different than what AzureOpenAIAPI has, see below: is that causing issue using above code?

AzureOpenAI API Embedding Output: This works fine with volatile memory store

`    {"object": "embedding",
            "index": 0,
            "embedding": [
                -0.012779145,
                -0.0075187064,
                -0.017534792,
                -0.028241644,
                -0.018796766,`
                ...
}
                
LM Studio Embedding model output: 
`  {
            "object": "embedding",
            "embedding": [
                0.04841502383351326,
                0.026464618742465973,
                -0.17441967129707336,
                -0.03099326603114605,`
                ...
}

Format of the output JSON is exactly same except the precision of floating points.

**Comment by RogerBarreto** [comment]
Currently `OpenAI` connector has a strict precision set for floats, attempting to use it in non-supported precision scenarios will result in error.

Since this is a non-supported scenario I would recommend implementing a [IEmbeddingGenerationService](https://github.com/microsoft/semantic-kernel/blob/main/dotnet/src/SemanticKernel.Abstractions/AI/Embeddings/IEmbeddingGenerationService.cs) dedicated for that higher precision result.

More details from OpenAI SDK enforcement/limitations on float precision below:

- https://github.com/openai/openai-dotnet/blob/main/src/Generated/Models/OpenAIEmbedding.Serialization.cs#L100
- https://github.com/openai/openai-dotnet/blob/main/src/Custom/Embeddings/OpenAIEmbedding.cs#L108

**Comment by RogerBarreto** [comment]
@stephentoub, That's correct, actually this is the main reason, I updated the previous answer, thanks.
