### ISSUE TITLE
.Net: Bug: .NET MemoryBuilder AzureOpenAI extension methods missing

### ISSUE THREAD

**Issue by TheAsteroid** [microsoft/semantic-kernel#9374]
**Describe the bug**
Until version `dotnet-1.17.0` there were extensions methods to register `AzureOpenAITextEmbeddingGenerationService` on the MemoryBuilder. In `dotnet-1.18.0` AzureOpenAI has been migrated from the OpenAI library to its own library. However now the MemoryBuilder is missing these extension methods.

Original methods: https://github.com/microsoft/semantic-kernel/blob/dotnet-1.17.0/dotnet/src/Connectors/Connectors.OpenAI/OpenAIMemoryBuilderExtensions.cs#L29

I would have expected to find the extension methods here: https://github.com/microsoft/semantic-kernel/tree/dotnet-1.24.0/dotnet/src/Connectors/Connectors.AzureOpenAI/Extensions

**To Reproduce**
1. Create a `var memoryBuilder = new MemoryBuilder();`
2. Observe `memoryBuilder.WithAzureOpenAITextEmbeddingGeneration();` not being available as extension method.

**Expected behavior**
The `MemoryBuilder.WithAzureOpenAITextEmbeddingGeneration` extension methods should be available.

**Platform**
 - Language: C#
 - Source: `dotnet-1.18.0` and higher.

**Comment by markwallace-microsoft** [comment]
@TheAsteroid we are planning to deprecate `MemoryBuilder` in favour of our new Vector Data abstractions. Because of this we are not adding new extension methods that reference the older pattern.

Here's a link to the learn site documentation for the new memory abstractions, our recommendation is that you switch to using these.
[What are Semantic Kernel Vector Store connectors?](https://learn.microsoft.com/en-us/semantic-kernel/concepts/vector-store-connectors/?pivots=programming-language-csharp)
