### ISSUE TITLE
Bug: GetCollection throws away PointStructMapper

### ISSUE THREAD

**Issue by lilhoser** [microsoft/semantic-kernel#9609]
**Describe the bug**

See this bug filed last week:  https://github.com/microsoft/semantic-kernel/issues/9520

I pointed this out in the corresponding PR:  https://github.com/microsoft/semantic-kernel/pull/9523

```
var recordCollection = new QdrantVectorStoreRecordCollection<TRecord>(this._qdrantClient, name, new QdrantVectorStoreRecordCollectionOptions<TRecord>()
{
    HasNamedVectors = this._options.HasNamedVectors,
    VectorStoreRecordDefinition = vectorStoreRecordDefinition
});
```

You're missing 

```
PointStructCustomMapper = this._options.PointStructCustomMapper
```

**Comment by evchaki** [comment]
@westey-m - can you take a look?  @lilhoser - thanks for bringing this up.

**Comment by lilhoser** [comment]
FYI: I am able to bypass this by using a `VectorStoreCollectionFactory` when calling `AddQdrantVectorStore`.

**Comment by westey-m** [comment]
Hi @lilhoser. Thanks for logging the issue.

The approach we are recommending for configuring a custom mapper when using IVectorStore.GetCollection is via a factory, like demonstrated here: https://learn.microsoft.com/en-us/semantic-kernel/concepts/vector-store-connectors/how-to/vector-store-custom-mapper?pivots=programming-language-csharp#using-a-custom-mapper-with-ivectorstore

Passing a custom mapper to `VectorStoreOptions` is problematic since `VectorStore` can work with any data model.  The data model is only chosen later when calling `GetCollection`.  This means that strong typing isn't possible at `VectorStore` creation time, which is harder to use and easier to get wrong.  Multiple custom mappers may also need to be configured, as different data models may be requested via `GetCollection`.  This seems like an edge case though, which could be handled via implementing the factory.  Feel free to disagree if you think this is a common scenario. It would be interesting to learn more about what you are trying to do to see if we have any gaps.

Even having `HasNamedVectors` on `VectorStoreOptions` isn't maybe the best, since it assumes that all collections that will be used with the `VectorStore` has the same named vector state, but it is less problematic than the mapper, since it doesn't have the strong typing issues.

It is of course also possible to just register and use a `VectorStoreRecordCollection` directly.  `VectorStore` is mainly interesting if needing to create or access many collections with a store agnostic piece of code.

**Comment by lilhoser** [comment]
@westey-m Yes, I'm able to use the factory approach and I think it's better suited to the task. Thanks for the feedback!
